### PR TITLE
fake airdrop

### PR DESCRIPTION
**Pull request by ImdioR**
"ens.domainse.org",
		"blenderdao.xyz",
		"dao-maker.blog",

### CODE REVIEW

**Comment by frankywild** [comment]
> "ens.domainse.org", "blenderdao.xyz", "dao-maker.blog",

Hello ImdioR, can you point out where is the scam in this site ens.domainse.org? Also, remember to add just the main domain.

**Comment by ImdioR** [comment]
> > "ens.domainse.org", "blenderdao.xyz", "dao-maker.blog",
> 
> Hello ImdioR, can you point out where is the scam in this site ens.domainse.org? Also, remember to add just the main domain.

Hi
Sure

Ens.domainse.oeg this is a scma website with fake ENS airdrop 
Original website is https://app.ens.domains/ and airdrop is no longer available.

What about 3rd domain:
Main domain this is just web construct website. So i avoided to add main domain and ban the entire domain.

**Comment by frankywild** [comment]
> ens.domainse.org

If you only add "ens.domainse.org", they can create another path like "app.domainse.org" which won't be blocked. But if you add "domainse.org" you will block everything coming from that domain.

**Comment by ImdioR** [comment]
> > ens.domainse.org
> 
> If you only add "ens.domainse.org", they can create another domain like "app.domainse.org" which won't be blocked. But if you add "domainse.org" you will block everything coming from that domain.

Yes, I know.
But i`m not 100% sure that entire domain domainse.org belongs to scammer.
ens.domainse.org for sure is the scam.
If you think that better to ban all domain, i`m ok with this !
Let me know if I should change the domain.

**Comment by frankywild** [comment]
> > > ens.domainse.org
> > 
> > 
> > If you only add "ens.domainse.org", they can create another domain like "app.domainse.org" which won't be blocked. But if you add "domainse.org" you will block everything coming from that domain.
> 
> Yes, I know. But i`m not 100% sure that entire domain domainse.org belongs to scammer. ens.domainse.org for sure is the scam. If you think that better to ban all domain, i`m ok with this ! Let me know if I should change the domain.

It looks like domainse.org is a fake site. I guess it's faking domains.org

**Comment by ImdioR** [comment]
> It looks like domainse.org is a fake site. I guess it's faking domains.org

Fixed, done!

**Review by frankywild — APPROVED** [review]

**Pull request merged**
