### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
```
"4ever-photo.com",
"app.dexprotocolserver.com",
"appsyncc.org",
"blockschainexplorer.com",
"blockschainssuppt.site",
"bondfold.help",
"colabconnect.net",
"collabassist.org",
"connectmanualdapp.live",
"dappsmobileconnection.com",
"defivalidators.net",
"dexprotocolserver.com",
"dodoswitch.com",
"errorfix.info",
"forevercollab.land",
"giftconnerz.buzz",
"hashbridge.org",
"maincollab.online",
"metachainconnect.com",
"naturalfarm-bonus.online",
"nftswaps.live",
"onlinevalidationsync.online",
"outerring-bonus.online",
"sinceredoge-bonus.online",
"swappynfts.online",
"swiftsyncs.com",
"syncvalidatedapps.com",
```

`onlinevalidationsync.online`
image

`dappsmobileconnection.com`
image

`connectmanualdapp.live`
image

<html>
<body>

Site | URLScan link
-- | --
onlinevalidationsync.online|https://urlscan.io/result/2a1e659e-5eb8-43db-b204-6806318be81e/
dappsmobileconnection.com|No UrlScan (GeoFence), but there is a screenshot.
connectmanualdapp.live|No UrlScan (GeoFence), but there is a screenshot.

</body>
</html>

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
h/t pastaMan and idclickthat

**Review by dubstard — COMMENTED** [review]
add more more
```
"4ever-photo.com",
"blockschainexplorer.com",
"blockschainssuppt.site",
"giftconnerz.buzz",
"naturalfarm-bonus.online",
"nftswaps.live",
"outerring-bonus.online",
"sinceredoge-bonus.online",
"swappynfts.online",
"syncvalidatedapps.com",
```

**Review by dubstard — COMMENTED** [review]
removed dupes
```
"collabwallett.com",
   "dappslauncher.com",
   "nonftsynchronization.com",
   "swiftdappsco.online",
   "wallsecureval.com",
```

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
ah some dupes in 1223, dang it, sorry

**Comment by jacogr** [comment]
It wastes a lot of time atm, have an idea for a solution around it.

**Comment by dubstard** [comment]
We usually merge them FIFO - fitst in first out, which is fine
this one is an edge case, due to PR having issues (IP instead of URL) and thus being on halt and a future one getting merged instead.
We agreed to check for pending PRs as well.

**Comment by ical10** [comment]
This is a valuable lesson, I'm really okay as long as we learn from this and can agree upon an improved workflow. Collaborate to win, as @dubstard said.

**Pull request merged**
