### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<body>

Site | URLScan link
-- | --
coinkin.org|https://user-images.githubusercontent.com/49607867/163528505-58c62fe6-ba88-48d3-b093-7477c6599abd.png
cryptosynchroniser.cloud|https://user-images.githubusercontent.com/49607867/163527524-a0dddd22-a2d2-4439-b780-42abcbe5789c.png
kontcoins.com|https://user-images.githubusercontent.com/49607867/163527480-7f0bca76-088c-49be-8ab1-6bb685c07d1e.png
legalbtcmining.org|https://user-images.githubusercontent.com/49607867/163527742-53875cb2-f551-453b-8105-c2d96f8c02c3.png
linuscointrade.net|https://user-images.githubusercontent.com/49607867/163528778-dba4f3ca-53a4-42c5-910f-5fc3ad46564e.png
mininings.com|https://user-images.githubusercontent.com/49607867/163529820-919a55c3-ea77-426c-9025-6018331b4794.png
ofxglobaltrade.com|https://user-images.githubusercontent.com/49607867/163528253-a7ac210d-edd6-4546-933e-4c60e99c4ceb.png
optimalcointrade.com|https://user-images.githubusercontent.com/49607867/163527695-fb1b6a16-30b0-430d-bc3d-b4a5da2b1e43.png
paulgoldhunter.com|https://user-images.githubusercontent.com/49607867/163528145-9900ec37-9d26-4309-bb9a-d5b6ed05bbf8.png
prefertoken.com|https://user-images.githubusercontent.com/49607867/163528407-8e84da9b-8b28-4f8d-a3d0-ead28cacd168.png
safebtcminings.com|https://user-images.githubusercontent.com/49607867/163528620-cf547256-633c-433a-8760-e187e1126e90.png
safemodetrading.com|https://user-images.githubusercontent.com/49607867/163528476-e593904a-3bd2-4bf2-b0d6-d6501f63b489.png
securefxtrade.org|https://user-images.githubusercontent.com/49607867/163528001-c47b40aa-2bf7-4561-9308-c60b79634423.png
unioninvestmentsfx.com|https://user-images.githubusercontent.com/49607867/163528214-f43b8a2a-3df2-4e90-8d92-09468f2b7727.png
webvalidauth.com|https://urlscan.io/result/2fca8203-f4d7-483f-b8e5-024f362a5980/dom/
assetsrectify.com|https://urlscan.io/result/5432a36c-36f7-4da8-a172-d7bd1f3fa6d6/dom/

</body>
</html>

Add Trust trading scams / Investment scams / Advance fee scams

The criminals lure victims to deposit money, then their portfolio “grows” on the imaginary trading platform.
Once a victim tries to **withdraw** their investment, the problems begin - need to deposit MORE money as fees, taxes, sometimes even extortion or to get doxxed to the IRS, other times simply not delivering the payments.
So they only take money, but never return it.

All sorts of assets supported, DOT included.

"coinkin.org",
image

"cryptosynchroniser.cloud",
image

"kontcoins.com",
image

"legalbtcmining.org",
image

"linuscointrade.net",
image

"mininings.com",
image

"ofxglobaltrade.com",
image

"optimalcointrade.com",
image

"paulgoldhunter.com",
image

"prefertoken.com",
image

"safebtcminings.com",
image

"safemodetrading.com",
image

"securefxtrade.org",
image

"tradex-financial.com",
image

"unioninvestmentsfx.com",
image

"utfxtrading.com",
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove primacycourierservice.com (non crypto related scam)
add cryptosynchroniser.cloud (phishing)

**Comment by dubstard** [comment]
✅Ready for review

**Review by dubstard — COMMENTED** [review]
w̶e̶b̶v̶a̶l̶i̶d̶a̶u̶t̶h̶.̶c̶o̶m̶
̶a̶s̶s̶e̶t̶s̶r̶e̶c̶t̶i̶f̶y̶.̶c̶o̶m̶

**Comment by dubstard** [comment]
[goodbye ](https://twitter.com/dubstard/status/1514837690465890310)
image

**Review by ical10 — APPROVED** [review]

**Comment by dubstard** [comment]
Thank you!

**Pull request merged**
