### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
dsappconnectwallet.ml|https://urlscan.io/result/f3dc1b93-27d5-4595-9d11-d9d019f21bb9/dom/
dapps-accesstool.com|https://urlscan.io/result/e85e27a2-4ed6-43f0-8fc5-9fefe24c7e83/dom/
dappsmain.com|https://user-images.githubusercontent.com/49607867/165233192-7ab36a12-5e7f-4587-9111-cd727835a988.png
imtokenau.icu|https://urlscan.io/result/bace012c-e5b7-4e23-b349-9fe2c463ab0c/dom/
im-token.farm|https://urlscan.io/result/03058354-97d7-4580-b345-183bb3655630/dom/
nodeprimedapps.online|https://urlscan.io/result/1de65bea-13b5-4e15-875e-047f64ee0563/dom/
nftio.online|https://urlscan.io/result/6656d32d-9864-4e6c-b061-068917021389/dom/
nfwalletconnect.com|https://urlscan.io/result/6cc74b88-fdbc-414b-a604-0a98bf685514/dom/
prodappfix.online|https://urlscan.io/result/2025ad46-5c33-40ba-8633-8515e7ca0680/dom/
pancakeswapfinaceconnect.ga|https://urlscan.io/result/8308476f-0db3-482d-b311-daf29bf89be2/
poa-bridge.com|https://urlscan.io/result/6c3bd32b-2630-4d02-9c4b-10d32e22b5f8/dom/
powerbridgemining.com|https://urlscan.io/result/75b17ccf-f614-473d-a669-e7bf974a2153/dom/
terra-bridge.com|https://user-images.githubusercontent.com/49607867/165232231-360b2ef5-61be-4cdc-9ba2-06ebbd7004b6.png
tokenmi.net|https://urlscan.io/result/5d26aeca-b2d5-4dbe-a152-d294fa3bc9f5/dom/
wab-synchronise.com|https://urlscan.io/result/1ac916b2-6eea-4a83-989b-5dd5838236e2/

</body>
</html>

add 
```

		"bscwalletconnect.com",
		"coinwallets.xyz",
		"dapp-eth.center",
		"dapps-accesstool.com",
		"dappsmain.com",
		"fixtodapps.com",
		"im-token.farm",
		"imitoken.club",
		"imtokenau.icu",
		"imtokens.farm",
		"metamask-faq.info",
		"metamask-verifyprocess.com",
		"nftwalletsauth.com",
		"nfwalletconnect.com",
		"nodeprimedapps.online",
		"powerbridgemining.com",
		"poa-bridge.com",
		"prodappfix.online",
		"shibutoken.site",
		"synchrosinteractive.com",
		"terra-bridge.com",
		"tokenauthservice.com",
		"tokenconect.online",
		"tokenmi.net",
		"tokens-claim.com",
		"truistunlock.com",
		"trustwalletsltd.net",
		"wab-synchronise.com",
		"walletconnectappweb.com",
		"walletconnectives.com",
		"webcoins-synchronize.info",
```

Regarding `kusama.escobaw13.xyz`
I don't know what is this, but it does not look good, as 

- 1. It is hiding the contents (geofenced bad content, if you don't match the allowed countries list you get google)
- 2. Things like `escabar private` and `ScamTeam` in the subdomains
- 3. xyz 1 dollar TLD
image
image

blocked

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
duplicate removed   "addressauthenticate.com",
    duplicate removed   "bestdappsfix.com",
    duplicate removed   "connectswalletdapp.com",
    duplicate removed   "dappssmartlaunchpad.com",
    duplicate removed   "syncwebtokenapp.com",

**Review by dubstard — COMMENTED** [review]
add
		"poa-bridge.com",
		"nftio.online",
		"connecttrust.digital",
		"kusama.escobaw13.xyz",
		"metamask-verify.co",
		"metamasks-extension.bmlvirtualconsultants.com",
		"metamask-verify-update.com",
		"dsappconnectwallet.ml",
		"walletpolkadot.net",
		"uniswapwbridge.com",
		"app.uniswap.org.pool-liquidity.sbs",
		"pool-liquidity.sbs",
		"metamask.com.4523544325432.bar",
		"4523544325432.bar",

**Comment by dubstard** [comment]
✅Ready for review

**Review by ical10 — APPROVED** [review]
Looking good!

**Pull request merged**
