### PR TITLE
Update address.json

### PR DESCRIPTION
**Pull request by michalisFr**
Added an address for polkadot.deals

### CODE REVIEW

**Review by jacogr — APPROVED** [review]
Thank you. Probably need to get it in all.json As well - but don’t do That. Will add a CI step that adds unknowns from here in there automatically. (With exclusions)

**Comment by jacogr** [comment]
Ummm... was wrong, it was in the list. Anyway, not sure why I missed the address check then - must have been sleeping on the job.

**Comment by michalisFr** [comment]
The URL was in all.json but the address was missing from addresses.json. Probably not reported.

But I see the address hasn't been added to the JSON after all

**Comment by jacogr** [comment]
It is there - https://github.com/polkadot-js/phishing/blob/master/address.json#L95-L97

The refresh in the apps UI just has a cache to not try and load with each and every use. (Same with extension, believe it is 45mins before each refresh)

**Pull request merged**
