### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
dappnetwork.walletconnect.ga|https://user-images.githubusercontent.com/49607867/162601710-6caaa85b-7de0-499d-ac59-c463eec02802.png
walletconnect.gq|https://user-images.githubusercontent.com/49607867/162601901-d6db5756-6b40-4632-b00a-eeb0faa9ad2b.png
walletconnect.ml|https://user-images.githubusercontent.com/49607867/162602104-a0d1324c-b7ce-495e-ab6a-daef60394c5b.png
walletconnect.cf|https://user-images.githubusercontent.com/49607867/162602201-2c0d277e-4f6f-49aa-8f5b-159994d3af97.png
whitelistconnector.netlify.app|https://user-images.githubusercontent.com/49607867/162602534-baceb106-021c-4148-ae02-786e88747f94.png

</body>
</html>

[Some Freenoms.](https://twitter.com/dubstard/status/1461581618414505984)
"walletconnect.ga",
"dappnetwork.walletconnect.ga",
image
image

"walletconnect.gq",
image

"walletconnect.ml",
image

"walletconnect.cf",
image

"walletconnect.tk",
❌💻
"walletconnect.000webhostapp.com",
❌💻 

"whitelistconnector.netlify.app",
image

"kusama.website",
Not sure what is this, but there are folders that suggest bad things.
image

image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add "whitelistconnector.netlify.app",

**Comment by dubstard** [comment]
✅Ready for review

**Review by ical10 — APPROVED** [review]
LGTM, great job!

**Comment by dubstard** [comment]
thank you!

**Pull request merged**
