### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
multiwalletvalidation.com| https://urlscan.io/result/e8f53447-9271-4d4e-a33b-54cd0e7ab668/dom/
connectwalletcertification.com|https://urlscan.io/result/9469b5b8-856e-49fb-99f9-339f4f3ce048/dom/ 
leedswalletsauthentication.com|https://urlscan.io/result/970a0d9c-84a1-4d74-b689-cdd4d79296de/dom/
walletsvalidationnode.com|https://user-images.githubusercontent.com/49607867/163144225-72b39fd1-86ae-4b7c-b436-d3886dc5ddcd.png
</body>
</html>

`multiwalletvalidation.com`
multi wallet validation

`connectwalletcertification.com`
image

`leedswalletsauthentication.com`
image

`walletsvalidationnode.com`
image

Pre dupe list (spray and pray)
```
"accessdappsserver.net",
"apecoin-claim.net",
"apecoinclaim.in",
"apecoinclaimer.com",
"collabdappsconnect.com",
"connect-todapps.net",
"connectdapper.com",
"connectifyserver.net",
"connectmydapps.net",
"connectto-dapps.net",
"connecttodapps.net",
"connecttoyourdapps.net",
"connectwalletcertification.com",
"dapps-activate.net",
"dapps-activator.com",
"dapps-connector.net",
"dapps-tolink.net",
"dappscconnect.net",
"dappsconnector.net",
"dappserveraccess.net",
"dappslinksconnect.com",
"dappssyncdirect.com",
"dappstolink.net",
"dappstoolsairdrops.com",
"leedswalletsauthentication.com",
"linktodapps.net",
"linkverify-pp.com",
"metafixsolution.com",
"multiwalletvalidation.com",
"nftdappsconnect.net",
"nftdappsconnector.net",
"ready-tickets.com",
"rectidapps.com",
"rectifydappserver.net",
"unifiedwalletsvalidation.com",
"unifiedwalletsverification.com",
"walletsafefix.com",
"walletsvalidationnode.com",
```

Final list:
```
"accessdappsserver.net",
"apecoin-claim.net",
"apecoinclaim.in",
"apecoinclaimer.com",
"collabdappsconnect.com",
"connect-todapps.net",
"connectdapper.com",
"connectifyserver.net",
"connectmydapps.net",
"connectto-dapps.net",
"connecttodapps.net",
"connecttoyourdapps.net",
"connectwalletcertification.com",
"dapps-activate.net",
"dapps-activator.com",
"dapps-connector.net",
"dapps-tolink.net",
"dappscconnect.net",
"dappsconnector.net",
"dappserveraccess.net",
"dappslinksconnect.com",
"dappssyncdirect.com",
"dappstolink.net",
"dappstoolsairdrops.com",
"leedswalletsauthentication.com",
"linktodapps.net",
"linkverify-pp.com",
"metafixsolution.com",
"multiwalletvalidation.com",
"nftdappsconnect.net",
"nftdappsconnector.net",
"ready-tickets.com",
"rectidapps.com",
"rectifydappserver.net",
"unifiedwalletsvalidation.com",
"unifiedwalletsverification.com",
"walletsafefix.com",
"walletsvalidationnode.com",
```

Duplicates removed:
```
"dappserveraccess.net",
"dappslinksconnect.com",
"multiwalletvalidation.com",
"rectidapps.com",
"unifiedwalletsvalidation.com",
"unifiedwalletsverification.com",
"walletsafefix.com",
```

### CODE REVIEW

**Comment by dubstard** [comment]
removing dupes... (WIP)

**Comment by dubstard** [comment]
WIP (adding screenshots / UrlScan links etc)

**Comment by dubstard** [comment]
✅Ready for review

**Review by ical10 — APPROVED** [review]

**Comment by dubstard** [comment]
Thank you!

**Pull request merged**
