### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
apibridgnetwork.org|https://urlscan.io/result/5894504b-e538-4745-9ddc-65b6ac5bc83f/dom/
clientswcrectify.com|https://urlscan.io/result/2bb64b2a-5aee-40bf-b238-fb74512a062b/
dappauthenticator.net|https://user-images.githubusercontent.com/49607867/168526291-21f18737-9e94-4d2d-8eb8-10504427f8ed.png
defivalidatedapp.com|https://urlscan.io/result/166ec554-259a-4292-9e84-b4850874c9d2/dom/
dapptools.tech|https://user-images.githubusercontent.com/49607867/168528125-2e3ec47c-56bf-4734-ac99-375ff0e87c44.png
imtokent.pro|https://urlscan.io/result/a6833f68-3608-46d7-8c29-8de6d1c3999c/dom/
polkadotnetwork.io|https://urlscan.io/result/59ff4114-4282-4964-8c1d-8545fef3429b/
pockchain.net|https://user-images.githubusercontent.com/49607867/168518272-a42df3d0-2716-417f-8a92-7325ef0ad744.png
tokenmigrationio.xyz|https://urlscan.io/result/f7d8fa84-4d7e-4afb-85aa-36696f1351d4/
the-bridgechain.com|https://user-images.githubusercontent.com/49607867/168528581-4d7aadd6-8662-4117-a357-85d9809d8389.png
secureddappsprotocol.net|https://urlscan.io/result/04fd4dd7-39d3-417f-88ca-16cd912e524b/dom/
sec-tool.net|https://urlscan.io/result/2f4b0023-4e2c-42c8-97f3-5165d13cf3fa/dom
sync-dapps.net|https://user-images.githubusercontent.com/49607867/168527514-84953228-b843-4eaa-8db3-10d2625624bd.png
vault-linkingserver.live|https://user-images.githubusercontent.com/49607867/168519263-5cc4b9b5-6354-462a-aa73-362077051b39.png
validate-link.net|https://urlscan.io/result/987bf61a-f856-4fda-bbc6-9ef494e88920/dom/
walletsrectification.online|https://user-images.githubusercontent.com/49607867/168520246-b5acbcbc-1984-4ef3-8b5f-fda41bc2f40a.png
walletwhitelistvalidate.com|https://user-images.githubusercontent.com/49607867/168520654-da6aedf1-ab62-4c6f-aa7a-9f861fb930e6.png

</body>
</html>

"apibridgnetwork.org",
"click-connect.info",
"dapps-binanceprogram.space",
"decenterland.tech",
"dipfix.live",
"mainnetsetup.org",
"marketplaceaxinfinity.club",
"metamask.metacube.online",
"metamaskzendesk.com",
"pockchain.net",
"polkadotnetwork.io",
"sec-tool.net",
"secureddappsprotocol.net",
"thepolkadot.org",
"validate-link.net",
"vault-linkingserver.live",
"vitalik-etherx2.net",
"walletsrectification.online",
"walletwhitelistvalidate.com",

`pockchain.net` - the Polkadot logo on this one is named ```http://pockchain.net/wp-content/uploads/2022/05/1651744208777.png``` so including screenshot instead of URLScan (URLScan exists as well)
Just one hit, hmmm.
image

`polkadotnetwork.io` - Reg Ru = no more comments needed, REG RU alone is enough reason for blocking, don't @ me.
image

`thepolkadot.org` - OwnRegistrar  = deserves immediate block (paint is still fresh, no bad contents yet). Just created, empty opendir at the moment. Site resides on infra used **only** for scams. A rare occurrence where we are ahead of the scammers with this one.
image

`mainnetsetup.org` - Just created, empty opendir at the moment. Site resides on infra used **only** for scams, based on the revealing domain name "main net set up" - cool story bro - thus blocking in advance, rare occurrence where we are ahead of the scammers with this one as well.

`polkadot.one` - Not phishing, but endless links of referral ads to dubious services and torrents under the pretense of "watch free TV online", there is nothing free. (removed block, just flagging)
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove dupes
```
"metamask-nft.io",
"nodevalidators.org",
```

**Review by dubstard — COMMENTED** [review]
remove non URL 
```
"mainnetsetup.orgsync",
```

**Review by dubstard — COMMENTED** [review]
"airswallets.com",
		"clientswcrectify.com",
		"collablandwalletconnect.xyz",
		"dapp3-usdc.xyz",
		"dappauthenticator.net",
		"dapptools.tech",
		"defivalidatedapp.com",
		"evidenceconnectwonder.xyz",
		"imtokent.pro",
		"itokenapp-stonne.com",
		"metamaskwalletverification.com",
		"metamaskwebconnect.netlify.app",
		"rectifycavity.top",
		"sync-dapps.net",
		"the-bridgechain.com",
		"tokenmigrationio.xyz",

**Comment by dubstard** [comment]
✅Ready for review

**Review by dubstard — COMMENTED** [review]
remove torrent tracker, TV page or whatever this is
```
		"polkadot.one",
```

**Comment by dubstard** [comment]
✅Ready for review

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks Jaco

**Pull request merged**
