### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by thwjanssen89**
|Site    |Urlscan| Screenshot|
|-------|-------|-------|
| arkhamintiligence.com | subwallet | https://github.com/polkadot-js/phishing/assets/97024090/752639d6-41b6-45c3-9012-2e1b78998662 |
| bridge.connext.network | subwallet | https://github.com/polkadot-js/phishing/assets/97024090/2436a2cc-7f07-481c-94b6-f8afed27f6fe |
| tokens-arbitrurn.com | subwallet | https://github.com/polkadot-js/phishing/assets/97024090/00f76f48-0c15-47b1-8b06-fb201295e63a |

### CODE REVIEW

**Review by frankywild — APPROVED** [review]

**Comment by tann9949** [comment]
@frankywild Connext is a legit bridge website as well as arkhamintelligence

I think you're making a mistakes merging a PR here

**Comment by tann9949** [comment]
Here's an info on Connext Network
https://www.crunchbase.com/organization/connext-inc

**Comment by thwjanssen89** [comment]
I will remove these from the blacklist

**Comment by thwjanssen89** [comment]
The arkhamintelligence one really is a scam. The legit version:
https://www.arkhamintelligence.com/ doesnt appear in our repo. It also
doesn't get blocked by my polkadot.js extension ;)

I removed the connext one. The reason I thought it was a scam was because
it was also reported by some third party anti phishing parties who reported
it as well and because they use some very insecure practices for example
requiring to scan a QR code to connect to their bridge. This is a very
insecure and scammy way of doing things. But it does seem to be legit after
all so I removed it.

**Comment by tann9949** [comment]
Thanks for the fast response.

I appreciate your concern regarding making the end user as secure as possible. However, I would love to add some additional comments you provided [here](https://github.com/polkadot-js/phishing/pull/3670#issuecomment-1646759474).

In your reply, you mentioned:
> I removed the connext one. The reason I thought it was a scam was because
it was also reported by some third-party anti-phishing parties who flagged
it, and they pointed out some very insecure practices, such as requiring users to scan a QR code to connect to their bridge. This method is considered very insecure and scammy. However, it does seem to be legitimate after all, so I removed it.

Am I understanding this correctly, that by the term "insecure practice for scanning QR," you mean the walletconnect QR scan (as shown in the image below)?
image

If this is the case, then it's very normal to have a walletconnect QR displayed on the screen, as walletconnect requires mobile users to scan their QR code. This is a very common behavior that you can see in almost all dApps supporting walletconnect. 

Again, I appreciate your efforts in helping end users flag scam sites, but the QR code criterion doesn't really make much sense to me. I hope you take this feedback into account for future scam site checks because this can potentially resulted in a confusion to end users on Connext side as well.

**Comment by thwjanssen89** [comment]
Hi thats not common at all, the much more common way is a pop up of your
crypto wallet. A qr code is very obvious attack vector which is why the
most secure dapps such as uniswap and aave don't use it. But it was just
one of the things. When I initially tried to look up the bridge I didn't
find anything about it online. It was also reported by several third party
phishing detectors which is also why I also combined with other things I
assumed it was a scam too. I actually found it reported in the phishing
repo of other professional phishing hunting companies.

**Comment by tann9949** [comment]
Hey, Thanks for the response again!

I still would want to clarify several points you made:


> Hi thats not common at all, the much more common way is a pop up of your
crypto wallet. A qr code is very obvious attack vector which is why the
most secure dapps such as uniswap and aave don't use it. But it was just
one of the things.

The QR design is a choice made by WalletConnect, and I would still insist that this is a normal and expected behavior for any WalletConnect users. If you browse to Uniswap or AAVE and select WalletConnect it also shows the QR code similar to how Connext shows:
Screenshot 2566-07-23 at 22 58 02
This is an expected behavior for ALL mobile wallets, especially for the case of WalletConnect which is also a mobile wallet.


> When I initially tried to look up the bridge I didn't find anything about it online. 

There's a tons of Connext article you can find online, with a simple google search
- https://www.coindesk.com/business/2023/06/14/interoperability-protocol-connext-labs-raises-75m-at-250m-valuation/
- https://blog.connext.network/
- You can even search their codes on a github: https://github.com/connext


> It was also reported by several third party
phishing detectors which is also why I also combined with other things I
assumed it was a scam too. I actually found it reported in the phishing
repo of other professional phishing hunting companies.

Can you clarify more on this point? Can you point out some "phishing hunting companies" you mentioned? That will be useful for us to further communicate with them and clarify if there's any misunderstanding.

**Comment by thwjanssen89** [comment]
Google learns from your search results. When I googled it first didn’t show
anything Crypto related.

Anyway just from the QR code thing I wouldn’t report it. The main reason
was that I check other anti phishing repos and professional anti phishing
companies reported it there so I copied those sites as they are very rarely
wrong.

You are right about walletconnect using a QR code design but it’s very rare
to be the first thing you see without clicking anything first. But again
that wasn’t the main reason and from that alone I would never report a
site.

Op zo 23 jul. 2023 om 18:18 schreef Chompakorn CChaichot <
***@***.***>

**Comment by tann9949** [comment]
Is it possible to provide the name or reference to those professional anti-phishing companies?

**Comment by thwjanssen89** [comment]
There are so many, like chainpatrol, ironguard, walletguard. I don't know
where I found connext in specific anymore. I report so many sites each
day.  But to give you an idea how I find some of the sites I report. I go
to for example the metamask phishing repo here:
https://github.com/MetaMask/eth-phishing-detect/pulls and these often
collaborate with some companies like for example chainpatrol and they
regularly update the repo with phishing sites. I often copy those into our
repo as well.

**Pull request merged**
