### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
dappactions.com|https://user-images.githubusercontent.com/49607867/165889033-3d966bd2-2a10-4f93-8629-66b347468489.png
intellsyncedapps.online|https://user-images.githubusercontent.com/49607867/165888677-90cbc1d5-9c60-42f6-92d3-4b64d009d877.png
lezconnectwalle.com|https://user-images.githubusercontent.com/49607867/165888870-5882e2e6-29fc-465b-a1d0-52e0b70277c9.png
onlinerectifynodes.com|https://urlscan.io/result/71481bbc-6c0e-4ac7-b791-fa9a29060fd2/dom/
rectifydapp.online|https://urlscan.io/result/6cbd4e12-db01-48f3-97e9-749a83a50619/
secureddapps.org|https://user-images.githubusercontent.com/49607867/165888458-5e88ea52-b37d-4ca0-893a-42243e3a3c1c.png
twrectify.com|https://user-images.githubusercontent.com/49607867/165888908-0b313f82-c637-417d-85cf-a7e9c2ce1d85.png
tokenpockeet.xyz|https://user-images.githubusercontent.com/49607867/165888972-c540628a-74bc-40bd-b1b2-893cf7625ec4.png
validatornode.org|https://urlscan.io/result/5deb391a-0c5c-4a08-9d38-4d3c0aeb414e/dom/
vault-connecting.live|https://urlscan.io/result/1953d307-24bb-4cee-a1e8-146d8babe188/dom/
wallconnect.xyz|https://urlscan.io/result/7e2e8315-a066-4526-bb73-757e619d0634/dom/

</body>
</html>

"atomicwalletrectify.com",
"currency-developer-crypto.xyz",
"dappactions.com",
"dappresynchronize.online",
"dappstoken.online",
"dappwalletvault.com",
"defidappsprotocol.online",
"digitalwalletconnect.xyz",
"flowtoken.pro",
"intellsyncedapps.online",
"lezconnectwalle.com",
"metamask333.com",
"metamaskis.com",
"metamasks10.com",
"mining-dapps.biz",
"mystoresetup.xyz",
"mytdapp-alerts.com",
"privacy-wallet.online",
"pulsexramp.live",
"rectifyatomicwallet.com",
"rectifydapp.online",
"rectifyhiveon.online",
"secureddapps.org",
"shinainutoken.com",
"tokenpockeet.xyz",
"tokenvalldator.com",
"twrectify.com",
"user-terabridge.xyz",
"validatornode.org",
"vault-connecting.live",
"wallconnect.xyz",
"wb3dapp.com",
"wwweb3token.com",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicates
 +   "dappstoken.online",
    +   "rectifydapp.online",
    +   "rectifyhiveon.online",

**Review by dubstard — COMMENTED** [review]
"acentoken.com",
remove (site is blank)

**Review by dubstard — COMMENTED** [review]
fix "secureddapps.orgen", to be "secureddapps.org",

**Review by dubstard — COMMENTED** [review]
remove
		"arranged.herokuapp.com",

**Review by dubstard — COMMENTED** [review]
add "onlinerectifynodes.com",
remove blank line

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Pull request merged**
