### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by ical10**
|Site|Urlscan|
|--|--|
|altsupport.tools|https://urlscan.io/result/99d291bb-5bc9-4355-8478-3be8473a7952/|
|app.bestdappfixes.com|https://urlscan.io/result/31487513-5b0c-48bc-bed8-f3b054d88537/|
|chainresolver.com|https://urlscan.io/result/65147278-cd36-4b3b-9731-b941e16c2375/|
|decentralizedsync.herokuapp.com|https://urlscan.io/result/6aab8630-2fdf-4147-9182-9db83abd31e1/|
|dev-wcerrorfix.pantheonsite.io|https://urlscan.io/result/f11c67c2-d251-494f-9ffd-1292a2157720/|
|host-node.net|https://urlscan.io/result/68ad1e73-14d1-4b55-85ea-19a97b7bb630/|
|quickvalidatewallet.netlify.app|https://urlscan.io/result/ddcb7d04-66fb-49ed-b33e-01d558b10a2a/|
|reloaddefibsc.com|https://urlscan.io/result/e9dbb789-7cd6-4289-9d34-0546359c598a/|

### CODE REVIEW

**Comment by ical10** [comment]
ready for review 👍🏻

**Comment by dubstard** [comment]
Tip Top! One heroku and one netlify, neat!
Also some other similar service provider (pantheon)

**Review by dubstard — APPROVED** [review]
All good

**Comment by ical10** [comment]
Thanks dub!

**Pull request merged**
