### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
polkadotup.net|https://urlscan.io/result/e2f78bf6-4723-4fac-b82a-f3016039de19/
syncwithmycolab.me|https://user-images.githubusercontent.com/49607867/162665527-4c54371f-2dbf-4520-972a-b3d952a09bbd.png
wallet-poleygon.technology|https://user-images.githubusercontent.com/49607867/162668189-c9aa4c0d-5eab-4f20-bd7d-2abdffc96393.png
polkadotgive22.com|https://urlscan.io/result/539f42f1-43ad-4f58-bc2c-dfff9c142c19/
polkadotgive.com|https://urlscan.io/result/de8b5fc4-a13b-40aa-83d9-fd8fe21fdcf1/
polkadotgive22.com|https://urlscan.io/result/f9f5bdce-a652-49e6-b360-250bc1659f90/
polkadotx22.net|https://urlscan.io/result/ee3ba68d-4be3-43e3-8629-3ef8a148e695/
polkagive2.net|https://urlscan.io/result/c4986d1a-49f5-424c-93f1-85f6ca3be6fb/
polkagive22.com|https://urlscan.io/result/104ddd34-6794-4226-b2d8-cc5e8a2714f6/
polkaup22.net|https://urlscan.io/result/b35b879d-c73a-4303-8a9a-515a4db7a006/
polkaupx2.com|https://urlscan.io/result/bc96e561-23f3-4eba-b016-d52d7b4d8fd2/
polkadouble.com|https://user-images.githubusercontent.com/49607867/162678147-a597ddba-2cf6-4655-ad62-503af1cb3e46.png
polkadouble2.com | https://urlscan.io/result/c7807534-e46c-4d85-bce1-4675567a9586/

</body>
</html>

add

"polkadotup.net",
"wallet-poleygon.technology",
"account.pega-support.com",
"pega-support.com",
"syncwithmycolab.me",
"ondo.claims",
"ondo.buzz",
"cryptohubdapp.netlify.app",
"wacondauto.com", - when adding it was OK, then it suddenly became a duplicate ⁉ 
"polkadotgive22.com",
"polkadotgive.com",
"polkadotgive22.com",
"polkadotup.net",
"polkadotx22.net",
"polkagive2.net",
"polkagive22.com",
"polkaup22.net",
"polkaupx2.com",

polkadouble.com
image

polkadouble2.com
image

polkadotgive22.com
image
IP backlisted so heavily, it hurts the reputation of ALL future sites tied to this host, get rekt.

polkadotup.net
image
same wallet as in #1358
100% confident that the same criminal group is behind this one, due to the walet being unchanged.
```
polka2022.net
polka22.net
polkadot2022.net
polkadot2x.net
polkadotevent2022.asia
polkadotevent2022.net
polkadotevent22.net
polkadotevents.asia
polkagiveaway.net
polkagiveaway22.net
x2polkadot.net
x2polkadotevent.net
x2polkaevent.net
```
polka22.net
image

polkagive2.net
image

polkadotgive.com
image

polkaup22.net
image

polkaupx2.com
image

⚠ATO twitter handle from 2013, 21K followers
image

🤡All to get cancelled, kbai
image

Check out how many sock puppets they have spawned, all to get their URLs non working hahahah. 

🚫Spam campaign cancelled.

image

wacondauto.com
image

syncwithmycolab.me
image

wallet-poleygon.technology
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add 
		"polkadotgive22.com",

**Review by dubstard — COMMENTED** [review]
remove duplicate "wacondauto.com",

**Comment by dubstard** [comment]
✅Ready for review

**Review by dubstard — COMMENTED** [review]
More, same scam, same IP
		"polkadotgive.com",
        "polkadotx22.net",
        "polkagive2.net",
        "polkagive22.com",
        "polkaup22.net",
        "polkaupx2.com",

**Review by dubstard — COMMENTED** [review]
+
"polkadouble2.com",
"polkadouble.com",

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
thanks

**Pull request merged**
