### PR TITLE
dot-event . org

### PR DESCRIPTION
**Pull request by NukeManDan**
image

### CODE REVIEW

**Comment by NukeManDan** [comment]
> unless you have a concrete URL with parameters, user agent and IP based in a given territory the fake "polkadot" clone will redirect you to the real world site
scammers will spam users with DMs, do account takeovers, hack high profile twitter and youtube profiles and rename them to elon musk or gavin and fake a "giveaway"
the bad website's hosting is hidden via a reverse nginx proxy

also from the reported on discord.

**Comment by dubstard** [comment]
thanks for the amazing fast reaction!

**Review by jacogr — APPROVED** [review]
Thank you!

**Comment by jacogr** [comment]
This one is problematic - at least in the extension it does not get properly detected with the redirect. It did actually work correctly in 0.36., but not in 0.37.1 - so the fix for "open in new" tab made this one break.

Will look to see what can be done and build in a fix & patch for the redirect-override.

**Comment by jacogr** [comment]
The `polka-*` addresses are probably also worth adding. These things may make a comeback.

Funnily enough, looking at the code of most of these, there are only a handful of scammers that are copying sites, I guess this is very visible from the redirects and same look-and-feel that is all-over. In some cases the scammers are even re-using the same chain addresses.

**Pull request merged**
