### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
cachedetect.net|https://user-images.githubusercontent.com/49607867/168414365-d2a5b8e3-b382-4837-8dad-8190f886062f.png
dappresolve.net|https://user-images.githubusercontent.com/49607867/168414224-18d795cd-a478-4c9d-8246-6e7820cf5704.png
dappwalletsauthorisation.com|https://user-images.githubusercontent.com/49607867/168414265-49df93e2-51ef-4575-ad95-ebb59f887e5f.png
token-pocket.biz|https://user-images.githubusercontent.com/49607867/168413182-62b54512-99b2-40a2-973d-991cee7e0724.png
tokendn1.club|https://urlscan.io/result/a3d6e09e-cbea-4aec-b845-49b599783c04/dom/
synchroniization.com|https://user-images.githubusercontent.com/49607867/168413245-72713a74-c67c-4fa8-828f-86c10c2f452b.png

</body>
</html>

add
	"buterinevent.com",
		"cachedetect.net",
		"denemesitem.store",
		"bsc-metonask.com",
		"connectwalletprotocol.xyz",
		"synchroniization.com",
		"tsltokenio.com",
		"247metamaskrapidresponse.com",
		"buterinevent.com",
		"coinbasewallets-up.com",
		"connectwalletprotocol.xyz",
		"dapp-calo.runmetamask",
		"dappwalletsauthorisation.com",
		"imtoken-3s.xyz",
		"imtoken-5t.xyz",
		"imtoken-6w.xyz",
		"imtoken-9r.xyz",
		"imtoken-fa.xyz",
		"imtokenio.club",
		"metamask-wallet-verification.com",
		"metamasksl.com",
		"mywallet-metamask.com",
		"polingon-wallets.site",
		"synchroniization.com",
		"token-pocket.biz",
		"token9.xyz",
		"tokendn1.club",
		"wallet-token.xyz",
		"wallets-polingon.site",
		"wallets-polingons.site",
		"walletsyncronization.com",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicates
"buterinevent.com",
"connectwalletprotocol.xyz",
"synchroniization.com",
"metamask-wallet-verification.com",
"walletsyncronization.com",

**Review by dubstard — COMMENTED** [review]
add +
dappresolve.net

**Comment by dubstard** [comment]
✅Ready

**Review by dubstard — COMMENTED** [review]
`dapp-calo.runmetamask` -> `dapp-calo.run`

**Comment by dubstard** [comment]
✅Ready

**Review by ical10 — APPROVED** [review]

**Comment by ical10** [comment]
Looks great!

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
