### PR TITLE
Update address.json

### PR DESCRIPTION
**Pull request by dubstard**
add getpolkadot[.]us
12rpYzbZHLmM83UcAuudQWr4cdb6xVCCe2brMQeno5isbSwK
image

### CODE REVIEW

**Review by jacogr — COMMENTED** [review]
Not sure what hapenned here ... it seems to touch every line in the file?

**Comment by dubstard** [comment]
Apologies for touching every line, I only wanted to add one new URL + wallet.

The bad site has been registered yesterday.
image

**Comment by jacogr** [comment]
Yes, not 100% sure what is wrong here but something was re-written which makes me jittery to merge since I can spot the addition which is 100%, but no idea why the rest all show changes. So not sure what is up - dunno if it is specific, change in character set here or something else.

Since these are consumed by tools, not sure if it is parsable since I can't see what the all-line changes are, hence my trepidation for it as-is. (And don't want to stomp over you by making another PR, but would greatly appreciate if the PR only have the specific addition)

**Comment by dubstard** [comment]
Apologies for my mistake.

**Comment by jacogr** [comment]
Will merge, just checked the merge process on CI and it will rewrite all of them again, so it should pickup if there are any non-parsable issues.

**Comment by jacogr** [comment]
Closing. Added it alongside the auto-check in #153

**Pull request closed without merging**
