### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
5 wallet connect badboys

note: only 2 of them have polkadot as wallet choice 
image
image

### CODE REVIEW

**Comment by dubstard** [comment]
whoops something broke 😓

**Comment by jacogr** [comment]
I will look into that break. It is a new check, but optional since it does analysis.

**Review by jacogr — APPROVED** [review]
Thank you.

**Comment by jacogr** [comment]
These must be profitable, there are millions of them.

**Comment by dubstard** [comment]
I track scammer wallets [here ](https://github.com/dubstard/scripts/blob/master/crypto%20scam%20wallets) and well enough some of them have accumulated millions of worth of crypto, tokens and stable coins alike $$$

If I ever "win the lottery" and have a gazzillion USDC I guess I would be very grateful to have tools like **RenProtocol** or **TornadoProxy**

But from my current PoV they are used almost exclusively by fraudsters to trade wash, in order to cover their tracks with stolen funds, which then get sold on P2P or OTC markets

Maybe those services are also used legit users who prefer anonymity (and not publicly buying uniswap socks for 60K or an crypto punk NFT for 4200 ETH to flex)

Now after Ledger conveniently leaked all users have a hardware wallet's addresses, this "anonymity" bit is sorta defeated for many anyway.

So the vast majority of users who remain using RenBTC and Tornado proxy are criminals, ransomware actors, pump and dumpers, fake ICO owners and other trade washers, and volumes are insane.

Even one successful extortion or stolen crypto hack fuels the sams for years ahead, as registrars are keen on collecting money in BTC fromJhon Doe registered with an temporary email address.

That way even if an attorney signed subpoena gets dispatched the service providers literally do not know who they are dealing with.

So in an age where everybody and everything is tracked, those guys still fly under the radar, with the caveat that they may never leave their country, as visiting airports is kinda dangerous when you are on FBIs list haha.

The other ungrateful bit is nobody thanks you if you save a person from phishing, as they woudnt even understand it, while if you save a man from drowning in a river, everybody will thank you.

**Pull request merged**
