### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<body>

Site | URLScan link
-- | --
[activateftfinance.com](https://twitter.com/Namecheap/status/1516635591814922245)|https://urlscan.io/result/a0ae8f04-b197-4d4c-aee4-83664491e60c/dom/
[astrofxplus.com](https://twitter.com/dubstard/status/1516647524748115969)|https://user-images.githubusercontent.com/49607867/164156971-016497d6-4d77-44c1-8f04-d0b48a418741.png
bswapstoken.com|https://urlscan.io/result/acb44d35-552f-4acb-bc60-ac5ae3559bd4/dom/
[connect.terraconnection.net](https://twitter.com/Namecheap/status/1516639376050171904)|https://user-images.githubusercontent.com/49607867/164157409-5ec1f958-0d9a-42f3-86ce-717058fc77b3.png
[financehalix.com](https://twitter.com/Namecheap/status/1516649194680950784)|https://user-images.githubusercontent.com/49607867/164157088-b27e8be1-aab0-4b93-9a18-dff02c7837ba.png
[xtrememinners.com](https://twitter.com/Namecheap/status/1516641878741078017)|https://user-images.githubusercontent.com/49607867/164157241-ce35538e-6147-4cfc-9d6a-92cd3f0c0876.png

</body>
</html>

`activateftfinance.com`
image

`astrofxplus.com`
image

`financehalix.com`
image

`bswapstoken.com`
image

`connect.terraconnection.net`
image

"xtrememinners.com",
image

add
"activateftfinance.com",
"astrofxplus.com",
"babydogenfft.online",
"batch-dollar.cfd",
"bit-miner.io",
"bitinvestsolution.com",
"bnb-fund.top",
"boredapeyachtclub.mint-early.com",
"bswapstoken.com",
"bzm-dollar.top",
"connect.terraconnection.net",
"correctiontoken.online",
"cryptnode.tech",
"crypto-now.org",
"dappfixerror.com",
"easy-crypto.world",
"financehalix.com",
"friend-fund.bar",
"fundsgaterecovery.net",
"global-trustexpert.com",
"guaranteedinvestmentfund.org",
"henexcapital.com",
"instantwalletdashport.online",
"internationalcapitalgrowth.com",
"liquidity-airdrop.info",
"mint-early.com",
"nodeinterface.flowex.online",
"paxfulnow.com.currently-tec.com",
"rectificationconnectservices.com",
"seedifiyfund.net",
"spiraltrades.com",
"sprout-invest.com",
"summertrades.com",
"support.wallethelp.online",
"terkswap.net",
"terraconnection.net",
"walletaccessrecovery.network",
"wallethelp.online",
"walletvalidation.online",
"meta.xrectify.live",
"xrectify.live",
"xtrememinners.com",

### CODE REVIEW

**Comment by dubstard** [comment]
WIP screenshots / urlscans

**Comment by dubstard** [comment]
✅Ready for review

**Review by dubstard — COMMENTED** [review]
removing 		
"edunaire.figlive.com",
"edutude.figlive.com",
"figlive.com",

They also had `postaz.figlive.com` which is also gone?
Defacement incident? or mass hosting?
Either way bad content seems gone.

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Pull request merged**
