### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
digitaldnodeapp.com|https://user-images.githubusercontent.com/49607867/165681839-4efdf69f-c098-47ba-aa2d-74d038b51563.png
nodesmainnet.com|https://urlscan.io/result/d6c42fb9-ffc1-4adf-af5c-2a3cf664ed50/dom/
mobilewalletstools.com|https://user-images.githubusercontent.com/49607867/165682090-755349d6-1897-4744-822f-86b6365e56ab.png
walletvalidationdapp.info|https://urlscan.io/result/b5683ca1-9268-4c10-9660-1c3882dbe570/dom/
dappstools.xyz|https://user-images.githubusercontent.com/49607867/165682291-30b26453-1f06-45be-8e4e-7861520ba195.png
rectifywebwallet.com|https://urlscan.io/result/16a69f01-df2c-4fe7-bd03-22304a4fbd26/dom/
rectifywalletdapps.com|https://urlscan.io/result/a4383936-e9a6-426e-9d7e-dcf7c6f41f8a/dom/
nodesmainnetdapp.com|https://user-images.githubusercontent.com/49607867/165682695-283320c3-888e-4d6c-86bc-e583e8575ff2.png
mobilewalletstools.com|https://user-images.githubusercontent.com/49607867/165682793-3b416256-37da-458b-9209-3eddcebafb0b.png
onlinewebauths.com|https://urlscan.io/result/1dbbbc1a-06bc-476c-8085-f996c755d177/dom/

</body>
</html>

"cn-metamask.me",
"connectwalllet.net",
"dapp2.xyz",
"dappstools.xyz",
"debugconnect.com",
"expert-crypto.org",
"extensiondapps.com",
"lmtokenco.com",
"m-imtokem.net",
"mobilewalletstools.com",
"nextrowallets.com",
"nodesmainnet.com",
"nodesmainnetdapp.com",
"onlinewebauths.com",
"pi-dapp.xyz",
"rectifywebwallet.com",
"v2-multibridge.net",
"validatedapp.online",
"walletvault.info",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove dupes:
    +   "rectifywalletdapps.com",
    +   "walletvalidationdapp.info",

**Review by dubstard — COMMENTED** [review]
add
"metamask.walletverification.in",
"walletverification.in",
"metamask-re.jatra-apps.org",
"tokenconnectprotocol.com",
"walletsynchronapps.cc",
"dappswalletsecured.us",

**Review by dubstard — COMMENTED** [review]
add "digitaldnodeapp.com",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Pull request merged**
