### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
dwintrectifier.com|https://urlscan.io/result/56c951f5-7e34-4b24-9f88-d9672ef621b5/dom/
web.onlineresync.site|https://urlscan.io/result/05444b1a-aeb6-4189-832f-40d8a13256d2/
app.hectatrade.com|https://user-images.githubusercontent.com/49607867/164383018-f4af2b5c-e6e0-4a52-9c12-1a80139ebb8e.png
bifrostsync.com|https://user-images.githubusercontent.com/49607867/164384764-0e777e21-8dbf-470b-a76c-6673c12db85b.png
walletfix.link|https://user-images.githubusercontent.com/49607867/164384583-24bb8338-1ef6-4ef8-8c0e-e7dc706c3513.png

</body>
</html>

add

		"app.hectatrade.com",
		"bifrostsync.com",
		"claim-mnlth.com",
		"collabs-land.live",
		"dwintrectifier.com",
		"hectatrade.com",
		"polkabot.network",
		"swapnfts-community.com",
		"validationdapplaunch.com",
		"walletfix.link",
		"onlineresync.site",
		"web.onlineresync.site",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add "polkabot.network",

**Comment by dubstard** [comment]
there is also `polka-dot.network` 🤡

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
