### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
algoconnect.live|https://user-images.githubusercontent.com/49607867/164910938-fcd014f2-a132-416d-9146-a2466ea7e201.png
connectifyxrypt.live|https://user-images.githubusercontent.com/49607867/164906437-b582e93c-519e-42b3-9a38-f044f75263c5.png
combinewallet.com|https://user-images.githubusercontent.com/49607867/164902985-bbaa5f89-c069-4252-a84a-bf57079f7547.png
websvalidate.digitalsynconline.online|https://user-images.githubusercontent.com/49607867/164902143-b1095765-de3b-44b2-ae5d-d232e280c041.png
dexapplaunch.co|https://urlscan.io/result/c1a8d4b9-0476-44ac-a0a0-509c6f986dba/dom/
imtoken-ap.icu|https://urlscan.io/result/fb7c782f-b032-4ca4-ad4f-710600f3b53c/dom/
digitalencrypt.online|https://urlscan.io/result/f8629167-ccde-469a-bf8a-816ca2067786/dom/
claimnft.lankyexpresscourier.com|https://user-images.githubusercontent.com/49607867/164908994-23ea8144-1234-4973-b5c9-0c982c912d9e.png
fixcheck.digitalsynconline.online|https://user-images.githubusercontent.com/49607867/164909045-e138c57c-9433-4041-8be3-7c06cb799279.png
deficonnectionpad.online|https://user-images.githubusercontent.com/49607867/164909156-6ed0dd9b-05c0-43a0-9abe-154e6ba7a5f6.png
liveconnectsapp.info|https://user-images.githubusercontent.com/49607867/164909234-7f1b39c5-e481-4c7a-acfd-ff46fda5b25d.png
primecoinsea.com|https://user-images.githubusercontent.com/49607867/164909355-bf04d511-34c7-477d-a0ac-719b6f6bbe63.png
invest.xentrades.com|https://user-images.githubusercontent.com/49607867/164909959-3d0338de-0774-478f-85a4-53fdec3d45a4.png
prochev.net|https://user-images.githubusercontent.com/49607867/164910005-c8c10afc-3c73-4605-9a92-fd02274ad286.png

</body>
</html>

```
		"algoconnect.live",
		"claimnft.lankyexpresscourier.com",
		"coinsinvestment.org",
		"combinewallet.com",
		"connettofixissues.online",
		"deficonnectionpad.online",
		"dexapplaunch.co",
		"digitalencrypt.online",
		"digitalsynconline.online",
		"fixcheck.digitalsynconline.online",
		"karafuru.gifts",
		"lankyexpresscourier.com",
		"lauchcollabapp.com",
		"launchvalidator.co",
		"liveconnectsapp.info",
		"primecoinsea.com",
		"recofund.com",
		"tradfem.com",
		"websvalidate.digitalsynconline.online",
		"imtoken-ap.icu",
		"multiconnect.live",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add
"bitforex-gains.co.uk",
		"cryptolead.org",
		"cyber-tools.xyz",
		"financequity.com",
		"invest.xentrades.com",
		"primecoinsea.com",
		"prochev.net",
		"profit-guarantee.uk",
		"xcoinsea.com",

**Review by dubstard — COMMENTED** [review]
remove duplicate "primecoinsea.com",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
