### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<body>

Site | URLScan link
-- | --
chaindappsconnect.com|https://user-images.githubusercontent.com/49607867/163765544-c5c3e23b-2f7b-4159-a125-d05c018e3f44.png
dappdefichains.com|https://user-images.githubusercontent.com/49607867/163764383-6963ff2a-86a9-4b02-85d3-6e31932fce90.png
dappsconnectchain.com|https://user-images.githubusercontent.com/49607867/163764424-45808805-28f9-4e9a-a824-be63ae9e4790.png
dappspublicchains.com|https://user-images.githubusercontent.com/49607867/163764773-6be4eef2-d97d-4f81-bc5e-fee1cdab1710.png
webconnectappsync.com|https://user-images.githubusercontent.com/49607867/163765278-f6b727c8-028c-4082-ae5c-b6338fcf3256.png

</body>
</html>

add 
"app-bogged.finance",
"appsaccess.org",
"boggeb.finance",
"chaindappsconnect.com",
"connectaccount.online",
"dappdefichains.com",
"dappspublicchains.com",
"defi-go.me",
"mainnetwalletconnects.com",
"sun-flower-land.com",
"wallet.appsaccess.org",
"appsaccess.org",
"walletconnectrectification.support",
"webconnectappsync.com",

`chaindappsconnect.com`
image

`dappdefichains.com`
image

`dappsconnectchain.com`
image

`dappspublicchains.com`
image

`webconnectappsync.com`
image

<body>

Real|Fake
-- | --
bogged.finance|boggeb.finance
bogged.finance|app-bogged.finance
sunflower-land.com|sun-flower-land.com
mirror.finance|mirrorfinanceio.com

</body>
</html>

### CODE REVIEW

**Comment by dubstard** [comment]
WIP

**Review by dubstard — COMMENTED** [review]
add "dappsconnectchain.com",

**Review by dubstard — COMMENTED** [review]
add "chaindappsconnect.com",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Pull request merged**
