### PR TITLE
Remove NFT site

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/polkadot-js/phishing/issues/969

### CODE REVIEW

**Comment by jacogr** [comment]
cc @dubstard cc @michalisFr cc @ical10 

Could you please review and check

**Comment by ical10** [comment]
Tries flipping this domain for at least $100.
I guess it's still okay?
Screen Shot 2022-01-21 at 13 59 14

**Comment by michalisFr** [comment]
Sorry for being late to the party, but I agree this looks harmless (for now), so whitelisting was the right approach. I'll report them though for monitoring, in case their usage changes in the future.

**Comment by dubstard** [comment]
cyber squatting is from 1999 and should die

**Pull request merged**
