### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
via0.com|https://urlscan.io/result/18ce7ca2-9245-41f6-b0b4-9f54bff97f18/dom/

</body>
</html>

"via0.com",
image

### CODE REVIEW

**Review by jacogr — COMMENTED** [review]
This one doesn't look Polkadot or even crypto-ecosystem related at all, what am I missing?

**Comment by dubstard** [comment]
> This one doesn't look Polkadot or even crypto-ecosystem related at all, what am I missing?

I have no idea what is the generic page via0.com.

The thing that bothers me is this walletconnect phish, which does include polkadot as well as far as i can see (check screenshot)
`https://via0.com/ipfs/QmcHkUNSzNnwwBudKvdU6VJS1FKVz9XwizBqsRGviDydtp?filename=indxx.html`

**Comment by dubstard** [comment]
> seems like they store the assets on ipfs and then present them with this `via0.com`, it's getting more sophisticated

image

The same is also valid for `fleek.co` which we have already blocked, thus I figured the same can apply for this one, based on the similarity - misuse of legitimate service.
image

**Review by jacogr — APPROVED** [review]
Thank you, yes it makes sense. Didn't see that path. O, boy... new tricks to look out for.

**Pull request merged**
