### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<body>

Site | URLScan link
-- | --
astarnetworks.useapp.org|https://user-images.githubusercontent.com/49607867/163959336-7f2b56bf-8672-41a9-9c1a-fd0780594311.png
cryptosync.vip|https://user-images.githubusercontent.com/49607867/163958602-62ec5f30-a5b2-46d4-af8f-0965fcd91988.png
vempire-ddao-rewards-claims-erc20-token.my.id|https://user-images.githubusercontent.com/49607867/163960393-7fdd1cc0-b815-4da7-ba2e-5c0601e75dd6.png
walletsauthenticator.xyz|https://user-images.githubusercontent.com/49607867/163960063-93840014-85ec-4f33-8b13-f936f4114d95.png

</body>
</html>

`apps.securetoken.live`
image
Interesting anti bot protection
image

`astarnetworks.useapp.org`
image

`cryptosync.vip`
image
`vempire-ddao-rewards-claims-erc20-token.my.id`
image

image

`walletsauthenticator.xyz`
image

```
"appnodecenter.com",
"authorizationtokenfix.com",
"authtokenfix.com",
"avalaunchapp.me",
"cakedefi-dfi-cstage.com",
"coinsbasess.com",
"collablandtools.com",
"connectcollabland.org",
"dapp.appnodecenter.com",
"dappfixedconnect.net",
"defifixprotocol.com",
"fixupmydappstokenwallet.org",
"holdersverify.online",
"importwallets.com",
"mynftconnectspad.com",
"portalsbridge.com",
"validatefixwallet.com",
"vallidationconnect.com",
"xn--blancer-8va.finance",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove duplicates
    ---   "connectaccount.online",
    ---   "connects-dapps.com",
    ---   "cryptossdapps.webflow.io",
    ---   "dappdefichains.com",
    ---   "dapptokenvalidator.com",
    ---   "walletconnectrectification.support",

**Review by dubstard — COMMENTED** [review]
add
		"securetoken.live",
		"apps.securetoken.live",

**Comment by dubstard** [comment]
WIP screenshots / Url scans etc

**Review by dubstard — COMMENTED** [review]
add

"dapp.swaplibra.com",
"swaplibra.com",

**Review by dubstard — COMMENTED** [review]
add
"vempire-ddao-rewards-claims-erc20-token.my.id",
"atari-rewards-claims-erc20-token.my.id",

**Review by dubstard — COMMENTED** [review]
add
"cryptosync.vip"

**Review by dubstard — COMMENTED** [review]
add
"astarnetworks.useapp.org",
"useapp.org",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks, apologies for taking too long with this one.

**Pull request merged**
