### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
07e96d43-381a-46a3-9c16-6daf97213efc.co|https://user-images.githubusercontent.com/49607867/162599634-868e0e52-4c2e-4fd2-8db1-6d881067083b.png
affixserve-activation.com|https://urlscan.io/result/a14b79dc-de46-4ff2-9908-c23ba8d32745/
connectionsystem-app.com|https://user-images.githubusercontent.com/49607867/162599685-89a67e05-527f-4604-b4f5-63af17235275.png
innodesettings.com|https://user-images.githubusercontent.com/49607867/162599685-89a67e05-527f-4604-b4f5-63af17235275.png
login-poigylon.technology|https://user-images.githubusercontent.com/49607867/162599690-b7921ba1-e05f-49b9-b679-f21cbc3a810a.png
wallet-poigylon.technology|https://user-images.githubusercontent.com/49607867/162599745-4cd44c65-e66b-4f4b-ad3c-986a74ffa520.png

</body>
</html>

"07e96d43-381a-46a3-9c16-6daf97213efc.co",
image

"affixserve-activation.com",
image

"boredapejachtclub.com",
"connectionsystem-app.com",

"innodesettings.com",
image

"login-poigylon.technology",
image

"wallet-poigylon.technology",
image

"wallet.connectionsystem-app.com",
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicate "cryptosdapps.webflow.io",

**Review by ical10 — APPROVED** [review]

**Comment by ical10** [comment]
ready @dubstard ? I need to merge mine after yours lol

**Review by dubstard — COMMENTED** [review]
remove 		"report.netcraft.com",

**Comment by dubstard** [comment]
> ready @dubstard ? I need to merge mine after yours lol

Just need to add the table and will add a comnent

**Comment by dubstard** [comment]
All good, thanks!

**Pull request merged**
