### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
authweb3utility.com|https://user-images.githubusercontent.com/49607867/162626749-97709cc9-14da-4c0d-8899-025ac77e4496.png
webhostdapp.com|https://user-images.githubusercontent.com/49607867/162625588-19a16fd2-26b1-4959-ae16-17df2cac6feb.png

</body>
</html>

"authweb3utility.com",
image

"webhostdapp.com",
image

### CODE REVIEW

**Comment by dubstard** [comment]
✅Ready for review

**Review by dubstard — COMMENTED** [review]
add authweb3utility.com

**Comment by dubstard** [comment]
✅Ready for review

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
thanks

**Pull request merged**
