### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<body>

Site | URLScan link
-- | --
airswaps.finance|https://user-images.githubusercontent.com/49607867/164050071-cec83f36-23dd-429f-ba27-73501127d35e.png
instantswiftfixed.com|https://user-images.githubusercontent.com/49607867/164048853-d9cfcd54-130d-4f50-b565-5008cf669e89.png
smartsyncsapps.com|https://user-images.githubusercontent.com/49607867/164036714-16f9b7e9-577b-46d5-8282-12ec45ea28dd.png
syncr-wallet.com|https://user-images.githubusercontent.com/49607867/164035400-9fb5091b-a310-4b06-9ae4-1bde0ab94375.png
walletzauthentication.com|https://user-images.githubusercontent.com/49607867/164029601-5eead850-6ee2-4b7a-93de-e134b2e96248.png
takeypro.com|https://user-images.githubusercontent.com/49607867/164047995-8f45b75f-6e9d-440a-af2e-e044c22eba87.png
universaldex.exchange|https://user-images.githubusercontent.com/49607867/164067405-95bb2c1c-0886-4474-bfd6-552a442106f8.png
secure.wc-connect.info|https://urlscan.io/result/1749701f-4f72-4581-814e-63cacd7ab8dc/
wc-connect.live|https://user-images.githubusercontent.com/49607867/164046101-18fc2d59-63b3-4928-a57e-bd2356727f1e.png

</body>
</html>

"airswaps.finance",
image

"instantswiftfixed.com",
image

"takeypro.com",
image

"secure.wc-connect.info",
image

"smartsyncsapps.com",
image

"syncr-wallet.com",
syncr-wallet com_SITE

"universaldex.exchange",
image

"walletzauthentication.com",
image

"wc-connect.live"
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
+
	"airswaps.finance",
		"betterswap.finance",
		"chainfix.bond",
		"colabconnect.land",
		"dificapitol.com",
		"livenodeauthorization.com",
		"nftcollabportal.com",
		"protonscanner.com",
		"soldrops.org",
		"sync-shield.com",
		"trustwalet.top",
		"wfree.digital",

**Review by dubstard — COMMENTED** [review]
add

		"secure.wc-connect.info",
		"wc-connect.info",
		"wc-connect.live",
		"instantswiftfixed.com",
		"livenodeactivation.com",
		"takeypro.com",
		"pancakedex.live",
		"kibainuspace.com",
		"universaldex.exchange",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thank you

**Pull request merged**
