### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
assetauthenticate.net|https://user-images.githubusercontent.com/49607867/165484079-6694c4ca-2913-44cc-8cf1-c47cab1a9c03.png
dappsendorse.net|https://user-images.githubusercontent.com/49607867/165484961-20affa35-3e75-45c7-aafa-ed84a88fccb0.png
dapps-linker.net|https://user-images.githubusercontent.com/49607867/165486525-214fc5a2-4463-4dfb-8e18-e109cb5c0df8.png
giveaway-token.tech|https://urlscan.io/result/579e3d6a-3762-492e-9a25-9734d784fd16/dom/
n.tokenbank.link|https://urlscan.io/result/193a9e96-37f9-427c-974f-b2d6e463573d/dom/
walletconnect.nftswhitelist.info|https://urlscan.io/result/e925ebc8-b9fe-4fb6-b159-6086233e037d/dom/
tusrtwallet.buzz|https://urlscan.io/result/fadb09f7-ad72-4f41-860a-28f103881213/dom/
suptokens.com|https://user-images.githubusercontent.com/49607867/165482217-ee156b90-44e2-4a6e-846d-e3bc9a8f62c3.png

</body>
</html>

h/t Bunny

(updated list without the duplicates, which were removed)
"appersconnect.com",
"assetauthenticate.net",
"assetverify.net",
"bancor-token.com",
"crypto-news1.com",
"crypto-verse.art",
"crypto-verse.xyz",
"cryptosecurefx.com",
"dapps-activator.net",
"dapps-authenticate.net",
"dapps-link.net",
"dapps-linker.net",
"dapps-unite.net",
"dappsaccess.net",
"dappsauthenticate.net",
"dappsauthenticator.net",
"dappsconfirm.net",
"dappsendorse.net",
"dappslinker.net",
"dappssupport.net",
"dappstool.org",
"dappsunite.net",
"dappsvalidator.net",
"dappsverify.net",
"divinerprotocol.live",
"dogecryptowallet.com",
"fidelity-pro.com",
"fidelityttrust.com",
"fidelityttrust.online",
"giveaway-token.tech",
"imtoken.tiger-pay.vip",
"infinitytokenswap.com",
"metamask-verifyprocces.com",
"metamask.com.verifytoken.in",
"metamask111.com",
"metamask365.com",
"multihexa.pw",
"multihexa.ws",
"n.tokenbank.link",
"opensea-activate.net",
"opensea-tool.com",
"openseaconnections.com",
"openseaverify.net",
"pancakeswap-tokens.com",
"pelisgoogledrive.net",
"project-connect.net",
"project-dappsconnect.net",
"project-sparkdapps.net",
"security-metamask.com",
"swap-pancakes.com",
"themetamask.io",
"token.crypto0.fr",
"walletconnect.nftswhitelist.info",
"walletspancake.com",
"welcome-dapp.com",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicates
```
"3dpouchsecure.xyz",
"apecoin-claim.net",
"apecoinclaim.in",
"apecoinclaimer.com",
"chainsconnectors.com",
"collabdappsconnect.com",
"dapps-activate.net",
"dapps-activator.com",
"dapps-connector.net",
"dapps-tolink.net",
"dappscconnect.net",
"dappsconnector.net",
"dappserveraccess.net",
"dappslinksconnect.com",
"dappssyncdirect.com",
"dappstolink.net",
"dappstool.net",
"dappstoolsairdrops.com",
"leedswalletsauthentication.com",
"metafixsolution.com",
"metamask6.com",
"multiwalletvalidation.com",
"nftdappsconnect.net",
"nftdappsconnector.net",
"rectidapps.com",
"rectifydappserver.net",
"walletsafefix.com",
"walletsvalidationnode.com",
```

add tld
"tokenbank.link",

**Review by dubstard — COMMENTED** [review]
add
"dappsai.online",
"metamask365.com",
"metatoken-ico.trade",
"metatoken.win",
"retrievetokens.com",
"securewalletsync.com",
"suptokens.com",
"tokensbit.com",
"trustwaletru.com",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thank you!

**Pull request merged**
