### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
app-erty.online|https://user-images.githubusercontent.com/49607867/166868295-c6cb5884-6399-44fd-8fd2-9ed9f17faf34.png
authorizedefi.network|https://user-images.githubusercontent.com/49607867/166868611-f4d464fe-dfa9-47b6-ab42-9e1502caa9f3.png
dapps-validation.org|https://urlscan.io/result/1dfa1281-2b09-48cb-967c-c3f5c850883d/
kwagh.click|https://user-images.githubusercontent.com/49607867/166868888-2da85fe9-099e-48ec-8258-ff2f2deb5fb7.png
synchronization.online|https://user-images.githubusercontent.com/49607867/166869096-86546efd-631f-4919-bafb-1400d252a394.png
chainlink.bond|https://user-images.githubusercontent.com/49607867/166869184-99b8d152-7404-46a0-99d1-59a7ecfcf316.png
liveappsaccess.com|https://urlscan.io/result/5a4741db-8583-402b-bd42-d87088cd54b4/dom/
tpocket.bet|https://urlscan.io/result/2b19cfe7-838f-41a5-a47c-b5f0cea275e1/dom/
stepnactivation.org|https://user-images.githubusercontent.com/49607867/166869964-10c7f56f-f528-4afb-bc81-26f351e9aa36.png
syncwalletdapps.net|https://user-images.githubusercontent.com/49607867/166870042-8e66d09d-5545-47aa-84b4-d109389b148b.png
rectificationnode.online|https://urlscan.io/result/bc4769e6-9108-4260-906a-f84aa304d5cc/dom/

</body>
</html>

		"app-erty.online",
		"authorizedefi.network",
		"dapps-validation.org",
		"kwagh.click",
		"netrectification.com",
		"synchronization.online",
		"syncwalletdapps.net",
		"tpocket.bet",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
fix commas

**Review by dubstard — COMMENTED** [review]
add "chainlink.bond",

**Review by dubstard — COMMENTED** [review]
add "stepnactivation.org",

**Review by dubstard — COMMENTED** [review]
"vallidation.com",

**Review by dubstard — COMMENTED** [review]
add
"angalwallet.com",
		"binance.cryptoecosystem.info",
		"chimera-wallet.co",
		"chimera-wallet.com",
		"coinbase.cryptoecosystem.info",
		"cryptoecosystem.info",
		"login-blockchain.cryptoecosystem.info",
		"olympusadao.financial",
		"olympusdao.ca",
		"xn--olmpusdao-19a.finance",
		"xn--olmpusdao-h5a.com",

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
WIP, adding some screenshots and URLscans, thanks for the approval

**Pull request merged**
