### PR TITLE
update all.json

### PR DESCRIPTION
**Pull request by ical10**
|Site|Urlscan|
|--|--|
|activeaccessapp.com|https://urlscan.io/result/ead0019a-fb67-4869-b190-72c5b5b45ad2/|
|activeappsfix.com|https://urlscan.io/result/d7c4bf06-4217-4c0c-a1e2-b3fd73c354fc/|
|authdappfiixedauthdappfixed.weebly.com|https://urlscan.io/result/28c5f925-11c5-42f9-be74-04865cd33968/|
|authdappfiixedautthdaapp.weebly.com|https://urlscan.io/result/a6bff2f5-51a6-4011-a5cf-2e698beb63ed/|
|authodapps.co|https://urlscan.io/result/0b1d68a3-c9a9-46d8-9849-ce448d6861a7/|
|dappsconnection.firebaseapp.com|https://urlscan.io/result/89f9c0fd-63c2-4368-91b6-70dc1ee5ba19/|
|fast-auth.com|(fearless) https://urlscan.io/result/49fbd02a-cbc8-4201-bad5-f9477db1cf0f/|
|maxtool.org|https://urlscan.io/result/b6e788b5-3cd1-4b92-9c1b-bf1057174fb9/|
|myactivationapps.com|https://urlscan.io/result/bb2f241f-1c4e-4752-9439-d405670aceb4/|
|mybit.zone|https://user-images.githubusercontent.com/14356826/168204952-d6d199bd-cff6-4614-8103-18e69b9b3e8d.png|
|mypageaccess.com|https://urlscan.io/result/510c6443-4fc9-420b-8d9f-d5d82ab950eb/|
|tokens-authservice.netlify.app|https://urlscan.io/result/8e752b58-0380-43a6-afd8-5223791c8dd2/|

### CODE REVIEW

**Comment by ical10** [comment]
ready for review ✅

**Comment by dubstard** [comment]
nice spots for the `firebaseapp.com` and `weebly.com` ones!

**Review by dubstard — APPROVED** [review]
All good

**Comment by ical10** [comment]
Thanks dubstard!

**Pull request merged**
