### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
livesecureconnect.com|https://urlscan.io/result/bf1ecc54-2fce-4d6c-bd25-5e0f9553f19d/dom/
liveactivationwallet.com|https://user-images.githubusercontent.com/49607867/168456940-471f96f2-86af-4948-81a7-654e852820de.png
dappswalletvalidations.com|https://user-images.githubusercontent.com/49607867/168458443-b831b84d-4888-4286-8e9e-67da50535616.png
main-panel.net|https://urlscan.io/result/ee7ee8fc-58c0-4709-8898-4ebd04f311d2/dom/
nahidharbourontario.com|https://user-images.githubusercontent.com/49607867/168458696-2c03183a-9d0f-42f2-8f28-136583b8b375.png
web3sycprotocol.com|https://urlscan.io/result/334e615c-49d0-491b-99c3-c6d6d6ab953f/dom/
walletconnect-dapps.ml|https://urlscan.io/result/3ecbcdc4-03e1-4845-a7d1-dd14eb60f2ea/dom/
walletverificationauths.com|https://user-images.githubusercontent.com/49607867/168458374-085ecd6f-18cb-4b03-8e88-1c108a57ec19.png

</body>
</html>

"dappswalletvalidations.com",
"imtokenpayl.online",
"liveactivationwallet.com",
"livesecureconnect.com",
"main-panel.net",
"metamask-nft.io",
"metamask.cash",
"metamask.io.web7896.web07.bero-webspace.de",
"metamaskcgn.xyz",
"metamasksecure.orgapp",
"nahidharbourontario.com",
"pancakesvvappsi.com",
"pancakeswap-finance-liquidity-pool.site",
"safe-panel.com",
"support.dappwalletconnect.xyz",
"unlock-keystore.online",
"validate-metamask.io.home-page.in",
"wallet.elrond.com.unlock-keystore.online",
"walletconnect-dapps.ml",
"walletconnect-dapps.cf",
"walletconnect-dapps.ga",
"walletconnect-dapps.gq",
"walletconnect-dapps.tk",
"walletconnect-dapps.top",
"walletconnect-dapps.icu",
"walletconnect-dapps.monster",
"web3sycprotocol.com",
"winsen.network",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add
		"walletconnect-dapps.com",
		"walletconnect-da.pps.ml",
		"swap-uniswap.xyz",

**Review by dubstard — COMMENTED** [review]
"walletsubconnect.com",
		"walletverificationauths.com",

**Review by dubstard — COMMENTED** [review]
"app.nodevalidator.net",
"nodevalidator.net"

**Review by ical10 — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
