### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
unlock-trustwallet.45-81-232-17.plesk.page|https://user-images.githubusercontent.com/49607867/164606615-0abee2d9-458f-46aa-8117-98ae7f33f9a6.png
trustwallet.com.verification.91-218-65-223.plesk.page|https://user-images.githubusercontent.com/49607867/164606793-c69e7618-b999-4d55-9221-eda830c509df.png
trustwallet-unlock.109-71-253-24.plesk.page|https://user-images.githubusercontent.com/49607867/164607067-7bfda1c1-96ba-4030-85b5-b7606befdc34.png
trustwallet-community.109-71-253-24.plesk.page|https://user-images.githubusercontent.com/49607867/164607223-8ef79b25-fe27-4462-8fcb-cdddd981c0a1.png
mytrustwallet-clientoverview.185-236-231-84.plesk.page|https://urlscan.io/result/5908cf32-6b0f-4bac-a3f6-71ff71af28cc/dom/
community.trustwallet.com.45-88-108-231.plesk.page|https://urlscan.io/result/c597c36d-14e0-4e7f-9ea0-2ec383107aa5/dom/
trustwallet.1.45-88-108-231.plesk.page|https://urlscan.io/result/17f20e7c-a931-4bfa-8864-12ba1fb2076c/dom/
trustwallet.109-71-253-24.plesk.page|https://urlscan.io/result/68a4a9fe-5bb9-43b1-859a-e593a42cf0b7/dom/
yourtrustwallet.wonderful-aryabhata.64-227-4-245.plesk.page|https://user-images.githubusercontent.com/49607867/164608657-849adb5e-c361-47cb-a7cd-e3914b7b9401.png
unlock-trustwallet.91-218-65-223.plesk.page|https://user-images.githubusercontent.com/49607867/164609141-d2f80787-6ab0-4ddf-8aba-12b12fceba9c.png

</body>
</html>

image

plesk.page bulk nuke crypto scams
```
"clientoverview-metamask.185-117-91-189.plesk.page",
"clientprotocol.metamask.team.securedesk.79-141-164-34.plesk.page",
"clientupdate-metamask.185-117-91-222.plesk.page",
"clientupdate.metamask.team.zendesk.185-236-231-184.plesk.page",
"community.trustwallet.com-recovery.45-88-108-231.plesk.page",
"community.trustwallet.com.45-88-108-231.plesk.page",
"community.trustwallet.com.91-218-65-223.plesk.page",
"login.trustwallet.45-88-108-231.plesk.page",
"metamask-kyc-standards.185-236-231-141.plesk.page",
"metamask-recover.185-236-231-227.plesk.page",
"metamask-regulation-server.45-88-108-231.plesk.page",
"metamask-support.clever-jones.35-203-88-159.plesk.page",
"metamask-support.pensive-mestorf.35-203-88-159.plesk.page",
"metamask-validation.179-43-176-123.plesk.page",
"metamask.community.unlock.45-81-232-16.plesk.page",
"metamask.io.91-218-65-223.plesk.page",
"metamask.io.flamboyant-black.111-90-143-152.plesk.page",
"metamask.io.kyc-regulations.107-172-188-102.plesk.page",
"metamask.io.kyc.regulation.45-88-108-231.plesk.page",
"metamask.io.support-center.45-88-108-231.plesk.page",
"metamask.io.zendesk.strange-napier.135-125-137-197.plesk.page",
"metamask.kyc.45-88-108-231.plesk.page",
"metamask.recovery.mode.185-100-87-154.plesk.page",
"metamask.recovery.mode.45-88-108-231.plesk.page",
"metamask.security.procedure.109-71-253-24.plesk.page",
"metamask.sharp-shirley.34-151-85-42.plesk.page",
"metamask.support.centrum.109-71-253-24.plesk.page",
"metamask.suspicious-sinoussi.34-92-30-20.plesk.page",
"metamask.wallet-verification.185-236-231-141.plesk.page",
"metamask.wallet.recovery.185-100-87-154.plesk.page",
"metamask.wallet.recovery.45-88-108-231.plesk.page",
"metamask.wallet.recovery.45-93-248-121.plesk.page",
"metamask.wallet.recovery.91-218-65-223.plesk.page",
"metamask.walletconnect.185-249-218-167.plesk.page",
"metamaskenfos.com.modest-franklin.35-203-88-159.plesk.page",
"metamaskrecover.179-43-187-217.plesk.page",
"my-trustwallet.45-88-108-231.plesk.page",
"mymetamask-clientarea.185-236-231-227.plesk.page",
"mymetamask-onlinesecure.185-117-90-230.plesk.page",
"mymetamask-onlinesecure.185-81-114-144.plesk.page",
"mymetamask-onlineupdate.185-80-53-115.plesk.page",
"mymetamask-overview.79-141-164-138.plesk.page",
"mymetamask-overviewonline.79-141-165-217.plesk.page",
"mymetamask-overviewpage.185-117-91-145.plesk.page",
"mymetamask-recoverupdate.79-141-165-17.plesk.page",
"mymetamask-updateform.185-80-53-113.plesk.page",
"mymetamask-updateonline.185-236-231-84.plesk.page",
"mytrustwallet-clientoverview.185-236-231-84.plesk.page",
"paxful.com-login.angry-gauss.34-97-37-234.plesk.page",
"paxful.com-login33.nervous-golick.35-203-61-10.plesk.page",
"paxful.com-login33.priceless-mayer.35-203-61-10.plesk.page",
"paxfulcom-login.priceless-mayer.35-203-61-10.plesk.page",
"paxfull.com-login.nervous-golick.35-203-61-10.plesk.page",
"paxfull.com-login.priceless-mayer.35-203-61-10.plesk.page",
"recovery-metamask-io.zen-cohen.141-164-62-92.plesk.page",
"trustwaflleby.peaceful-brattain.185-236-231-93.plesk.page",
"trustwallet-community.109-71-253-24.plesk.page",
"trustwallet-edison.45-88-108-231.plesk.page",
"trustwallet-online-recovery.45-88-108-231.plesk.page",
"trustwallet-unlock.109-71-253-24.plesk.page",
"trustwallet.com.91-218-65-223.plesk.page",
"trustwallet.com.s1.45-88-108-231.plesk.page",
"trustwallet.com.verification.91-218-65-223.plesk.page",
"trustwallet.community.com.45-88-108-231.plesk.page",
"trustwallet.festive-williamson.143-198-124-192.plesk.page",
"trustwallet.i.dreamy-chebyshev.109-71-253-24.plesk.page",
"trustwallet.i.vibrant-mirzakhani.45-81-232-17.plesk.page",
"trustwallet.lucid-robinson.143-244-162-16.plesk.page",
"trustwallet.recovery.community.109-71-253-24.plesk.page",
"trustwalletunlock.gifted-lumiere.138-68-99-93.plesk.page",
"unlock-trustwallet.45-81-232-17.plesk.page",
"unlock-trustwallet.45-88-108-231.plesk.page",
"unlock-trustwallet.91-218-65-223.plesk.page",
"walletconnect.com.metamask.91-218-65-223.plesk.page",
"yourtrustwallet.eloquent-jemison.137-184-141-8.plesk.page",
"yourtrustwallet.wonderful-aryabhata.64-227-4-245.plesk.page",
"zendesk.metamask.io.strange-napier.135-125-137-197.plesk.page",
```

### CODE REVIEW

**Comment by dubstard** [comment]
duplicates to be removed
    +   "clientupdate-metamask.185-117-91-222.plesk.page",
    +   "metamask.wallet.recovery.91-218-65-223.plesk.page",
    +   "mymetamask-onlinesecure.185-81-114-144.plesk.page",
    +   "mymetamask-overviewonline.79-141-165-217.plesk.page",
    +   "mymetamask-recoverupdate.79-141-165-17.plesk.page",
    +   "trustwallet-community.109-71-253-24.plesk.page",

**Review by dubstard — COMMENTED** [review]
removed duplicates

**Review by dubstard — COMMENTED** [review]
add 
"trustwallet.1.45-88-108-231.plesk.page",

**Review by dubstard — COMMENTED** [review]
"trustwallet.109-71-253-24.plesk.page",

✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks chief

**Pull request merged**
