### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
fingers crossed no dupes (will let the LGTM check and fix later if needed)
```
"acapolkadot.js.org",
"adidas-nft.art",
"anchorprotocol.online",
"aqt15rvrenr47nepncmgpzivae79polkadot.js.org",
"bridgeservices.online",
"camelneedlesnft.com",
"cex-crypto.com",
"coinbaseprocoreinfosecuresystems.coinbasewalletsecure.com",
"coinbasewalletsecure.com",
"coinfutureoptions.com",
"coinmining-capital.com",
"connected-for-you.services",
"connectingerrordap.com",
"cryptoplonic.com",
"digitalmintx.com",
"fixchainserror.com",
"fixwallab.xyz",
"icedapeharborclub.com",
"io-metamask.sytes.net",
"login-metamaskweb.com",
"mainnet-support.online",
"metamask-2.jana-app.org",
"metamask-secure.com",
"metamask-verifyprocesess.commm",
"metamask-wallet.xyz",
"metamask.help",
"metamask.icowallet-app.com",
"metamask.oxog.net",
"metamask.xn--onlin-b0a.xyz",
"metamaskio.serveftp.com",
"mint-metroverse.net",
"myedefisolutions.com",
"nftrader.dev",
"pandauniversenft.vip",
"securecryptowallets.org",
"supportmetamask-netlify.app",
"test-polkadot.js.org",
"validatordapp.co",
"wethepeoplenft.io",
"walletspy.io",
```

### CODE REVIEW

**Comment by dubstard** [comment]
`test-polkadot.js.org` dupe
and one `.commm` instead of `.com`

**Comment by jacogr** [comment]
The dupe check is a pain, aka CI could just remove those. But it then opens the door for spam PRs where they just add an already existing host and brand it as "new". I guess can adjust a bit to check for dupes (removing on merge), but ensure that there is at least one new one to make the check pass.

**Review by dubstard — COMMENTED** [review]
removed dupe

**Comment by dubstard** [comment]
Sorry, I was lazy and let the bot do the dirty work for me

**Review by jacogr — APPROVED** [review]

**Pull request merged**
