### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
1token-im.com|https://urlscan.io/result/9d1d5844-6d25-4fd3-be00-663fdf055f2e/
active.walletsauths.com|https://urlscan.io/result/8eed73d7-efc0-4133-8c54-a150b3984179/
collab-land-secure.com|https://urlscan.io/result/775d2853-238f-4767-a354-63976ad6e246/dom/
dapp-pool.live|https://user-images.githubusercontent.com/49607867/167241663-7edd1c87-85b8-4888-a915-48f4e5afa1ca.png
dappauthess.com|https://urlscan.io/result/d8bd6776-4f8a-4e39-ad40-d5a6f2cffae2/
defiease.net|https://user-images.githubusercontent.com/49607867/167241650-4a5d1713-e476-4d05-9c62-e7c5b7d4eb91.png
immmtoken.com|https://urlscan.io/result/2a664ca3-5bd9-4208-8e91-9c4865d95676/dom/
linkdappsdefi.com|https://urlscan.io/result/887eb99c-6eda-4900-8f6c-7445b0670be3/
multibridge.live|https://urlscan.io/result/3403c1ba-b275-41d1-aa02-76d9e2e934b5/
metamaskio.win|https://urlscan.io/result/b4ed00cc-9143-446f-b753-53a763beaef6/
node.thetatokenconnect.org|https://urlscan.io/result/bf50ec83-cd84-4969-8027-c5dc5057a548/
onlyappsauthenpoint.online|https://user-images.githubusercontent.com/49607867/167241893-1f4d4bf8-f097-4564-b771-baa7b83d7437.png
sphére.finance|https://user-images.githubusercontent.com/49607867/167241945-46490103-ac6f-438f-a5ff-d04a88560caf.png
step-app.live|https://user-images.githubusercontent.com/49607867/167242026-14fd11d1-7d09-44f3-8e10-a174125b24b0.png
thetatokenconnect.org|https://user-images.githubusercontent.com/49607867/167242034-591990ea-742f-41fc-8258-3579f2ddaa3f.png
twmnftcollectibles.com|https://user-images.githubusercontent.com/49607867/167242047-2863c63e-81a1-49f7-afbb-dac8636847df.png
wallectsyncfix.com|https://urlscan.io/result/26d36e72-3a8e-49ba-ba95-6081eb0da69c/
walletconnectsecurity.com|https://urlscan.io/result/30669460-199b-466e-8198-fbb60c1b90bd/dom/
walletsauths.com|https://urlscan.io/result/8eed73d7-efc0-4133-8c54-a150b3984179/

</body>
</html>

		"2fa.collab-land-secure.com",
		"collab-land-secure.com",
		"pads.defiease.net",
		"defiease.net",
		"metamask-connect.com",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
"otherdeed-airdrop.com",
		"onlyappsauthenpoint.online",
		"node.thetatokenconnect.org",
		"thetatokenconnect.org",
		"active.walletsauths.com",
		"walletsauths.com",

**Review by dubstard — COMMENTED** [review]
"step-app.live",
"multibridge.live",
"sphére.finance",
"twmnftcollectibles.com",
"wallectsyncfix.com",

**Review by dubstard — COMMENTED** [review]
"connectwallet-dapp.com",
"1token-im.com",
"walletconnectsecurity.com",
"linkdappsdefi.com",
"immmtoken.com",
"fix-dapps.com",
"dappauthess.com",
"blockchain-wallets-connect.ga",

**Comment by dubstard** [comment]
there is also this gem:
image
There does not appear to be any bad content at the moment, but quite a few red flags

**Review by dubstard — COMMENTED** [review]
image
`metamaskio.win`

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thanks!

**Pull request merged**
