### PR TITLE
added phishing site https://aquasync.pages.dev/

### PR DESCRIPTION
**Pull request by bipulhk**
added phishing site   https://aquasync.pages.dev/

### CODE REVIEW

**Comment by frankywild** [comment]
> added phishing site https://aquasync.pages.dev/

Hey bipulhk, that site is not showing anything for me, do you have a screenshot or a urlscan link?

Thanks!

**Comment by bipulhk** [comment]
Sure, the homepage is blank, but the actual phishing page is located at https://aquasync.pages.dev/dapps/wallet , also iam attaching the urlscan link.
https://urlscan.io/result/672e6034-8fe6-4307-893c-b0ba145c788e/compare
Thanks!

**Review by jacogr — APPROVED** [review]
Thank you.

**Comment by jacogr** [comment]
Screenshot for future reference -

image

**Pull request merged**
