### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by frankywild**
|Site    |Urlscan|
|-------|-------|
|activationaces.com|https://urlscan.io/result/059fc9cb-af46-41bd-a3b8-0ae42d83ca86/dom/|
|apexearner.com|https://urlscan.io/result/ded55370-f281-4198-abca-2b339df092b3/|
|app.kavaapp.net|https://urlscan.io/result/cdcc33eb-4024-479a-8642-acec40df4d29/|
|blockchainpumpcoin.com|https://urlscan.io/result/251b2fee-f045-4a5a-bcae-7a7b227b5e4e/dom/|
|dotsea.app|https://urlscan.io/result/92a63063-32cf-44c5-8774-134f1401f32e/|
|explanandaconsult.com|https://urlscan.io/result/d83f965b-b92b-4868-8a61-6edf59079f82/dom/|
|iglesiavozdedios.cl|https://urlscan.io/result/b7afe704-d8b8-46d9-bcc8-d94e87748b9d/dom/|
|itallsimple.com|https://urlscan.io/result/9fc3455e-5397-4453-a79a-68e9e94e5f78/dom/|
|luckyblockchain.org|https://urlscan.io/result/2c4ba35b-1fb6-47f3-9586-fa414360f330/|
|metablockchaiin.me|https://urlscan.io/result/61e41eb6-1754-47bf-9328-8ee8ede7ef42/dom/|
|multistalk.online|https://urlscan.io/result/d511afd5-0b66-4be0-a820-fa71624ee5a0/dom/|
|networkchainapi.net|https://urlscan.io/result/516f4ea5-e6b2-426d-b662-2bfc7b1e706e/dom/|
|securecryptoconnect.com|https://urlscan.io/result/7e8f9bdf-a610-47db-90b9-985c42998453/|
|smart-handshake.com|https://urlscan.io/result/920e2418-b57f-48cf-a3fe-2769d054bcd8/dom/|
|synnwallconn.online|https://urlscan.io/result/47576ebc-c0f0-4463-ad63-1a0576b4e513/dom/|
|web3rpcsync.com|https://urlscan.io/result/5a8ef9ca-679b-475e-b9cb-e78d7674a438/dom/|
|zellespay.com|https://urlscan.io/result/9be20d03-a52d-44fb-b03c-b8134017623a/|

### CODE REVIEW

**Review by ccris02 — DISMISSED** [review]
You should not be blocking IP addresses 
"49.12.117.192" is a Hetzner Server, a lot of Validator nodes run in Hetzner.

**Comment by dubstard** [comment]
We have had only 1 IP blocked until now.
Not sure what is the rule.
If the IP is a VPS blocking can be benefitial if the domain score is high (i.e. 100% of domains on this IP are bad)
But if the IP is shared and not a VPS blocking IP is not recommended.
<html><body>
<google-sheets-html-origin><style type="text/css"></style>

https://github.com/polkadot-js/phishing/pull/1267 | 162.222.226.37
-- | --



</body>
</html>

**Comment by frankywild** [comment]
Done guys!

**Review by dubstard — APPROVED** [review]
IMO some IPs are OK to block
For example All websites on IP address 8.210.104.235 are fraudulent, there is nothing else hosted on this IP besides phishing and scams.
https://twitter.com/dubstard/status/1519177447811473409
IMO this particular IP 8.210.104.235 would be OK to block and here is why

- 1. The abuse email inbox appointed to it is full, thus can not accept any new reports
- 2. This IP has ONLY phishing and fraud tied to it via DNS A
- 3. This is not a shared IP, but a VPS one. Meaning that someone has purchased it and uses it only for illicit purposes,

Just my  2c
Dub

**Pull request merged**
