### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
5gwalletfix.com|https://user-images.githubusercontent.com/49607867/165027805-db9439e9-6eb9-4059-b608-8373cf049fb0.png
allchainprotocol.com|https://user-images.githubusercontent.com/49607867/165027929-8fcc2351-545b-4a7b-b08c-44dd82a2e542.png
adestrade.com|https://user-images.githubusercontent.com/49607867/165028361-d719b650-3cd5-4eb7-a60d-1eef8bbfa8e5.png
bestnodesfix.com|https://urlscan.io/result/2616fb76-3659-4f23-9db3-6f38c4175f3c/dom/
cryptonanceinvest.com|https://urlscan.io/result/d4b142c8-fb07-464f-9563-3a1c0da324a8/dom/
swaplit.online|https://urlscan.io/result/bcfd2fb9-83e1-4f60-8e33-999a49e853e3/dom/
syncwalletsvallidation.com|https://user-images.githubusercontent.com/49607867/165029206-4082d423-e67b-442d-b0c4-0fb00fa01603.png
smartlaunchweb.com|https://user-images.githubusercontent.com/49607867/165032451-912bbfb8-bd7e-48c6-800d-18dadf0ff58e.png
onlinesmartapps.com|https://urlscan.io/result/8a6894a3-36f5-45a2-942e-998fa4b962cf/dom/
websrevalidate.online|https://user-images.githubusercontent.com/49607867/165028503-e3ca71b4-f69d-4104-a083-491b169cfd3d.png
walletautorization.info|https://urlscan.io/result/aaf0e2f3-4ff3-4bd5-8d37-000ccb30e6e7/dom/
walletaccesslink.me|https://urlscan.io/result/16115572-f298-4f76-a80d-ac036303d8c8/dom/

</body>
</html>

add
```		
		"5gwalletfix.com",
		"adestrade.com",
		"allchainprotocol.com",
		"app.syncwalletsvallidation.com",
		"blockchainminingspace.com",
		"connectionsynchronization.netlify.app",
		"cryptonanceinvest.com",
		"defikingdoms-com.xyz",
		"digitalfixx.online",
		"hello.privatemint.space",
		"privatemint.space",
		"homeconnectwalletpancakeswap.diskstation.org",
		"letverifynow.mrbasic.com",
		"letverifynowallcoin.mrbasic.com",
		"meettam.diskstation.org",
		"meta.diskstation.eu",
		"metamask-keyst.com",
		"metamask.beautiworld.live",
		"metamask.com.metamask-mmtoken.com",
		"metamask.io.amazingohosting.com",
		"metamask.io.metamaskauthorization.in",
		"metamask.manyuak.com",
		"metamaskapply.ddns.net",
		"metamaskk.dray-dns.de",
		"metamaskmtoken.amazingohosting.com",
		"metamaskmtoken.com",
		"metamaskverif.io",
		"native-metamask-io-2.cf",
		"onlinemetamask.camdvr.org",
		"onlinewalletverification.dnset.com",
		"safety-metamask.io",
		"swaplit.online",
		"syncwalletsvallidation.com",
		"tokens.native-metamask-io-2.cf",
		"topforexcrypto.com",
		"walletautorization.info",
		"walletrectification.network",
		"walletspancakeswapverify.com",
		"walletspancakeswapverify.com.bscwalletconnect.com",
		"wallgb.dd-dns.de",
		"webconnectappsync.com",
		"websrevalidate.online",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicate "webconnectappsync.com",
and nft site (not sure if scam or not)

**Review by dubstard — COMMENTED** [review]
add 
"airdrptrstwllt.xyz",
"turstwallet.club",
"dotverify.live",

**Review by dubstard — COMMENTED** [review]
add fake nft site, stealing seed phrase
"nftlqunchpad.xyz",

**Review by dubstard — COMMENTED** [review]
add

		"app.myaccessauth.com",
		"app.walletaccesslink.me",
		"bestnodesfix.com",
		"metadoctor.myappsio.online",
		"onlinesmartapps.com",
		"smartlaunchapp.org",
		"smartlaunchweb.com",
		"walletaccesslink.me",

**Comment by dubstard** [comment]
✅Ready for review

**Review by ccris02 — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
