### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
accountsynchronization.pages.dev|https://user-images.githubusercontent.com/49607867/167066133-c2ef37a8-eadf-43d9-907e-2af8c8d78c90.png
dapp-authentikator.xyz|https://user-images.githubusercontent.com/49607867/167066215-44fd8d92-5de8-4630-b376-d66b34706939.png
dappsync.nl|https://user-images.githubusercontent.com/49607867/167066460-4e7e1d26-080a-4bce-acb4-eeaa2ef05456.png
dapprestore.info|https://urlscan.io/result/ccebb7dc-aeec-4da5-baab-fc70cfb54bb8/
daapstoolkits.com|https://urlscan.io/result/1399d92e-36c2-45c3-a103-c3140df0205e/
imtoken991.com|https://urlscan.io/result/cf47a85c-b822-4e5f-af5c-dc9a4502edc7/dom/
imtoken992.com|https://urlscan.io/result/d97f5c6a-241c-4985-a053-b2eee46ba8a1/dom/
imtoken993.com|https://urlscan.io/result/161f2514-f8b0-4075-a03d-61e634544f43/dom/
imtoken995.com|https://urlscan.io/result/ccb58715-6ca9-4f50-8613-7b70f204be03/dom/
thedefipairedapps.online|https://user-images.githubusercontent.com/49607867/167070548-bf8eb396-9b6e-4136-8629-32ea02eae7c9.png
multi-entitychains.com|https://urlscan.io/result/44aaae7e-e025-442c-a7cb-dca358936c97/dom/
personalwallets.xyz|https://user-images.githubusercontent.com/49607867/167070437-df6a62a9-b666-42ec-abdd-cb61a47dd5cd.png
oracle-blockchain.vercel.app|https://urlscan.io/result/828c29f8-c3b6-46e5-b06e-4764e5017ee6/dom/
securedefinode.com|https://urlscan.io/result/5aea316d-a7d3-4ce1-b098-ad0752492321/
syncdappsdefi.com|https://user-images.githubusercontent.com/49607867/167070617-8ecdaa7c-4cf0-4983-a647-29f700078d6e.png
walletsgrid.company|https://user-images.githubusercontent.com/49607867/167070723-e6b82479-81a8-440c-bac4-acd045a605b3.png
wallsyncliveport.com|https://user-images.githubusercontent.com/49607867/167067068-43b94c2b-a37f-46ce-8baf-d52d892f0fae.png
web3rpcdapp.com|https://user-images.githubusercontent.com/49607867/167067110-21e49985-216f-4143-a2a0-b1a88a3ca022.png
webflow.ink|https://user-images.githubusercontent.com/49607867/167067171-bf6aab6e-e505-4c3d-b7b7-84a8fbc1b51a.png

</body>
</html>

h/t MegaMind 
```
		"accountsynchronization.pages.dev",
		"blockchainbridgeconnect.com",
		"bridgenode.surge.sh",
		"crypto-metamask-verifyprocess.com",
		"dapp-authentikator.xyz",
		"dappsync.nl",
		"getmetamask.com",
		"im-pay-mxcg39-token.xyz",
		"metamask-web.org",
		"metamask.extensionsu.xyz",
		"metamask.faviconkit.com",
		"metamask.io.ldown.pro",
		"metamask.io.vihax.com",
		"metamask.kyc4you.io",
		"metamaskcan.xyz",
		"metamasktoken.org",
		"mettammask.netlify.app",
		"multi-entitychains.com",
		"official-token.im",
		"oracle-blockchain.vercel.app",
		"oracledexapp.org",
		"secure.gulfcardinalbank.com",
		"securedefinode.com",
		"tokenofficial.pages.dev",
		"wallsyncliveport.com",
		"web3rpcdapp.com",
		"webflow.ink",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicate
add TLD

**Review by dubstard — COMMENTED** [review]
"daapstoolkits.com",
		"dappnetworkactivation.net",
		"dapprestore.info",
		"dappschainlink.com",
		"imtoken-vn.com",
		"imtoken991.com",
		"imtoken992.com",
		"imtoken993.com",
		"imtoken994.com",
		"imtoken995.com",
		"livedapp-online.com",
		"personalwallets.xyz",
		"smartdappfix.site",
		"syncdappsdefi.com",
		"synchronization.online",
		"terrabridge.website",
		"thedefipairedapps.online",
		"trustsewallets.com",
		"walletsgrid.company",
		"webunlockeer.com",

**Review by dubstard — COMMENTED** [review]
remove duplicates
  "dappnetworkactivation.net",
  "dappschainlink.com",
  "synchronization.online",

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Pull request merged**
