### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by frankywild**
|Site    |Urlscan|
|-------|-------|
|accountsvalidator.net|https://urlscan.io/result/c83ab275-92f2-4526-9e4d-954e023cf33a/|
|avanttrends.com|https://urlscan.io/result/a76f6108-8981-47bc-a829-08fdbba5b1b2/dom/|
|claimnft.live|https://urlscan.io/result/16fcc714-c012-4df8-bd43-7cd97e194518/dom/|
|correctionbot.org|https://urlscan.io/result/e935dd01-995e-4078-8941-c049ac10c1a9/dom/|
|expressprivacyfixr.com|https://urlscan.io/result/b9e4fc87-b002-4dcf-badb-26efa1d33a57/dom/|
|idols-tube.su|https://urlscan.io/result/e3a25961-7991-44a1-b651-2118e861d372/dom/|
|interfaceapi.co|https://urlscan.io/result/9ba0f399-4051-4db8-8031-23950921c52c/dom/|
|launchpad.sync-enjinstarter.com|https://urlscan.io/result/7af2bbe5-f983-4d6c-a642-e4d426effbe1/dom/|
|mymainnetimport.com|https://urlscan.io/result/44ea79ba-e378-4b9a-ae6f-2e2196acb2c5/dom/|
|pro-nft.io|https://urlscan.io/result/e4945ab1-a69e-4f55-b1ff-9e5ac315cd04/dom/|
|riotokenswap.com|https://urlscan.io/result/102d682f-0de7-4734-9dd2-4833414c00fa/dom/|
|sattota.com|https://urlscan.io/result/1f063daf-dc09-4c05-a903-3ff592e4c4b3/dom/|
|tokenconnet.online|https://urlscan.io/result/0e252421-4fbf-4758-88db-47718fae592a/|
|validate.syncwalletsinstantly.com|https://urlscan.io/result/6ef54e0c-ab21-4085-911d-428f6a65d545/dom/|
|walletliveconnecting.com|https://urlscan.io/result/9efc5b4c-820e-4339-a9e6-ffcad2907760/dom/|
|walletsconnetdapp.com|https://urlscan.io/result/b1c87c8e-148e-4ca4-ad09-872b37837f85/dom/|

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
LGTM

**Review by dubstard — APPROVED** [review]

**Review by dubstard — APPROVED** [review]
This is an approving review (test 2)

**Comment by jacogr** [comment]
@dubstard Just accept the invite.

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
I admit that I don't know how to accept the invite. I imagine it is something obvious which I missed. Sorry.

**Comment by jacogr** [comment]
You should have received a mail. I should also show up in either https://github.com/polkadot-js or https://github.com/polkadot-js/phishing on top.

**Comment by dubstard** [comment]
Got it, and yes I do have the mail, invite accepted!
image

I tend to ignore the github mail as I did something wrong and I don't know how to get rid of it because I am an utter nimrod, so it spams me constantly 😵
image

**Comment by jacogr** [comment]
Ok, so approve & merge will work now.

**Pull request merged**
