### PR TITLE
update all.json

### PR DESCRIPTION
**Pull request by ical10**
| Site | URLscan.com link |
| ------------ | ------------ |
|thetrolllerart.dvrlists.com| https://urlscan.io/result/b667dd6e-76f8-4694-9616-ff6d05da148e/ |
|web3connector.com| https://urlscan.io/result/d299e1ae-2c61-4512-a18b-d24fa7fbb2e5/ |
|cn59409.tmweb.ru| https://urlscan.io/result/0735803d-13c3-466c-9f94-d956aa2e4693/ |
|walletconct.co| https://urlscan.io/result/a92d0530-d96e-41d4-a97b-0e5626f5d680/ |
|polikadot.com| https://urlscan.io/result/b1eb6000-c09c-4a75-acec-26633e24918f/ |
|myauthnetwork.com| https://urlscan.io/result/cebf582b-b186-4991-af23-c0981a9c34ea/ |
|main-errorfix.live| https://urlscan.io/result/045adffb-632f-42d2-822f-34189665d34a/ |
|walletconnecting.co | https://urlscan.io/result/318765c4-2744-440f-8a4a-ea718778b0c7/ |
| walletconnect-web3.com | https://urlscan.io/result/3e4e9e20-2424-4e4d-b099-e267a3ddecfe/ |

thetrolllerart dvrlists com_SITE
web3connector com_SITE
cn59409 tmweb ru_SITE
walletconct co_SITE
polikadot com_SITE
myauthnetwork com_SITE
main-errorfix live_SITE
walletconnecting co_SITE
walletconnect-web3 com_SITE

### CODE REVIEW

**Comment by ical10** [comment]
added 

    "walletconct.co",
    "polikadot.com",

**Comment by ical10** [comment]
added

    "thetrolllerart.dvrlists.com",
    "web3connector.com",
    "cn59409.tmweb.ru",

**Comment by ical10** [comment]
added

`nodechain.me`
`walletconnecting.co`

**Comment by ical10** [comment]
added `walletconnect-web3.com`

**Review by jacogr — APPROVED** [review]

**Pull request merged**
