### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
dapps-validation.co|https://urlscan.io/result/8b5d6ac4-834b-42fa-a729-c1e8b811ea2a/dom/
dexchainpad.site|https://urlscan.io/result/0078c6e9-c74f-41d2-b650-8eab8bec8c41/
insuredapplite.co|https://urlscan.io/result/789fb9d0-6d0d-4b1a-98ee-b8faaa8d64c4/dom/
walletsync.online|https://user-images.githubusercontent.com/49607867/168990655-69e20771-f6bf-4c49-a1a3-f6a48ddee45d.png

</body>
</html>

Nice try:
image

"dapps-validation.co",
"meta-extension.net",
"stepn.engineer",
"appregistry.live",
"onlininfo.link",
"metamasf.net",

(h/t Cindy | serv.eth team)

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
"confirmpage.metamaskwalletverification.com",
"dappethereum.fun",
"dappethereum.online",
"dappethereum.xyz",
"dapps-validation.co",
"finance-v2-liquidity-swap.site",
"io.support-metamask.space",
"metamask-kycverif.com",
"metamask.cash",
"metamask.com.vn",
"metamask.io.cikgutekansiap.com",
"metamask.io.wallet-identification.divu.cl",
"metamask.io.wallet-identification.rwatelier.com",
"metamask.login.update.for.suspended.wallet.samirtomb.com",
"metamaske-extension.hmongtimes.com",
"metamaskwalletverification.com",
"sms.tokenconnectprotocol.com",
"support-metamask.space",
"tokenconnectprotocol.com",
"verify.walletsync.online",
"walletsync.online",

**Review by dubstard — COMMENTED** [review]
remove dupes
    +   "dapps-validation.co", (added twice by mistake)
    +   "metamask.cash",
    +   "metamaskwalletverification.com",
    +   "tokenconnectprotocol.com",

**Review by dubstard — COMMENTED** [review]
add "dexchainpad.site",

**Review by dubstard — COMMENTED** [review]
"globaltokenswap.com",
		"nfttrader.io-0xd8bcfffbf8dc67353cd0739f4f2ad487c657d5b0.trade", 
		"io-0xd8bcfffbf8dc67353cd0739f4f2ad487c657d5b0.trade",
		"insuredapplite.co",

**Review by dubstard — COMMENTED** [review]
"tokeniam.xyz",
"poligom.club",

✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thanks

**Pull request merged**
