### PR TITLE
Adding few newly registered phishing sites

### PR DESCRIPTION
**Pull request by net-null**
I’ve been working on adding sites to https://polkadot.js.org/phishing/. And this month I was able to add 480 websites. I have automated the parts of the process but the most time I spend is actually adding sites to the GitHub repository (formatting URL and placing them in alphabetical order). And that process is getting harder since we have more and more reported URLs. I was wondering if there could be a better way to block phishing sites.

1. Pull phishing URL’s from some phishing site databases. I have found this site https://pastebin.com/u/spamreports
2. User reportable Suspicious sites. Let’s say a user goes to a site and it looks and feels suspicions user then can click on the polkadot.js extension and mark it as “Suspicious” site gets added to “Suspicious List” next user would get a warning but would be able to go to the site if you get 10 users marking the site as “Suspicious” site gets added to list and it is blocked 
You could have moderators if they think the site is Phishing, they can verify it and it gets added to the blocked list.
3. If the user goes to a site that has specific keywords in the URL worn user about Phishing Sites, like do not paster Seed keys to URL’s t

### CODE REVIEW

**Comment by jacogr** [comment]
So, the volume is great, however it is a bit scattergun, i.e. it doesn't focus on Polkadot and ecosystem. So our PRs generally take a bit longer to go through since I check all of these to find if they have any relation to Polkadot/ecosystem and then extract address info (general phishing) from them. It is not a perfect science however, so for instance Atomic support Polkadot and there are obviously a lot of sites tragetting that wallet.

There are general phishing databases, see for instance Phishfort which does exactly hat you suggest - https://github.com/phishfort/phishfort-lists/ (they also pull Polkadot-specific ecosystem data from here)

**Comment by net-null** [comment]
Thanks Jaco for your input. I will narrow down the search to Polkadot and its Ecosystem. I do realize that Metamas is for ERC20 but I have seen with some of the new projects on Polkadot (Sora, Crust) they have an ERC20 token and they need to be moved to Polkadot. And that was the reason I have added it. I will check out the 
 https://github.com/phishfort/phishfort-lists/  it seems like a great project.

**Comment by jacogr** [comment]
I am not complaining - you are doing absolutely brilliant work here :)

Yes, Phisfort is really great since they pull from all lists across the whole blockchain ecosystem.

**Review by jacogr — APPROVED** [review]
Thank you!

**Pull request merged**
