### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
```
"7polkadot.js.org",
"connectwallet-kucoin.gq",
"connectwallet-kucoin.ml",
"cryptoverse-token.sale",
"cryptoxtoken.xyz",
"elongatetoken.me",
"elonkingtoken.com",
"enpolkadot.js.org",
"kusamaproject.com",
"kusamaprojects.com",
"metamask-recovery.net",
"metamask-walletconnect.ga",
"palcapolkadot.js.org",
"polkadot-wallet.net",
"polkadot-wallet.xyz",
"polkadottii3.co.uk",
"polkadotweb.js.org",
"restore-metamask.info",
"yourwalletconnect.online",
```

`kusamaproject.com`
`kusamaprojects.com`

Attempt to interact with the extension. 

I also stumbled upon 
`1polkadot.com.br` - seems safe
image

There is also
`polkadot.energy` where the email is tied to `holdpolkadot.com`
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupes
    -   "cryptocardapp.xyz",
    -   "elongainstoken.com",
    -   "kusamat.js.org",
    -   "metamask-recover-account.tk",
    -   "metamask-recovery.info",
    -   "metamask-recovery.org",
    -   "metamaskacouht.com",
    -   "metamaskacount.com",
    -   "metamaskapp.live",
    -   "metamaskverse.xyz",
    -   "metamaskwallet.cn",
    -   "nftokenswap.com",
    -   "oppolkadot.js.org",
    -   "restore-metamask.world",

**Review by jacogr — COMMENTED** [review]
polkadot.energy is known...

Need to get outside opinions on the kusama* projects

**Comment by dubstard** [comment]
What irked me is that they are very similar (1 letter difference, same registrar and hosting (AliDNS)
I am afraid to let it interact with the extension though.
I will remove them for now.

**Review by dubstard — COMMENTED** [review]
FP 
-"kusamaproject.com",
-"kusamaprojects.com",

**Review by jacogr — APPROVED** [review]

**Pull request merged**
