### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
allchaindapps.com|https://user-images.githubusercontent.com/49607867/167781842-3bcc8e9a-7e91-423d-8c8e-032a6a3a998a.png
connect.raritydapp.online|https://urlscan.io/result/f608a41b-112f-4e63-8193-f8c5cc01184c/
fixupalltokenwallets.com|https://user-images.githubusercontent.com/49607867/167778405-026145c8-e324-4bbe-a21d-8c3984fc2935.png
tokenim.red|https://urlscan.io/result/e01b9f22-e2bb-4ad3-bbbd-10ba4a2f6607/dom/
dappssynch.win|https://urlscan.io/result/0f8ba4bf-9894-4b02-8a19-539fce77f6be/
imtokens.run|https://urlscan.io/result/23f1cec0-b6e3-4dab-bf33-a009e66b4306/dom/
mainaffixrectify.com|https://user-images.githubusercontent.com/49607867/167780267-a5eb60e7-1af6-4802-bf28-bc82ce603cfa.png
noderectifysyncs.com|https://user-images.githubusercontent.com/49607867/167780444-be725e60-2d9f-4f99-996d-0155d1b98c5d.png
mainnode-sync.com|https://urlscan.io/result/734f8d04-32d7-436e-9718-cb7bafa7e9e7/
nftland-app.com|https://user-images.githubusercontent.com/49607867/167780776-c4e4b302-5975-45e9-a3e1-e1d7da8ecc28.png
tokenimk.top|https://urlscan.io/result/42b5f9aa-ff68-49ad-88b8-c478edadebcf/dom/
tokenpockent.info|https://user-images.githubusercontent.com/49607867/167780987-83a9c689-2639-4dc3-9420-c8950da15eab.png
mainaffix-sync.com|https://user-images.githubusercontent.com/49607867/167781336-d0e255ea-3f96-4a46-805e-8d620961d059.png
validateddappsconnect.com|https://user-images.githubusercontent.com/49607867/167782931-b06f329e-164d-48c2-b86f-5f2ba05c7325.png

</body>
</html>

"allchaindapps.com",
"chainsconnectingmaindappnet.com",
"chainsfixedmaindappnet.com",
"connect.raritydapp.online",
"dapp-eth.biz",
"dappaflixcwallet.net",
"dappai.net",
"dappssynch.win",
"download-imtoken-app.com",
"fixedapps.net",
"fixupalltokenwallets.com",
"imtoken1-3.com",
"imtokenapp.asia",
"imtokenapp.group",
"imtokenapple.xyz",
"imtokens.run",
"japsystems.com.tokenconnectprotocol.com",
"mainaffixrectify.com",
"metamask-eth.org",
"metamask-v.com",
"metamask-wallet-verification.com",
"metamask-x.com",
"metamask.info-mywallet.com",
"metamask.laconfianzacoop.com",
"metamask.raymasterbatch.com",
"metamaskreward.com",
"metamaskteam.online",
"metamaskverif.com",
"raritydapp.online",
"syncmainrectify.com",
"tokenapp.cloud",
"tokenim.red",
"tokenimi.top",
"tokenimk.top",
"tokenimk.xyz",
"tokenimo.top",
"tokenimo.xyz",
"tokenpockent.info",
"tokenpocket0.top",
"tokenpocketim.top",
"tokenpound.com",
"trustpad-dapp.com",
"trustpad-dapp.net",
"trustpad-tokens.com",
"trustpad-tokens.net",
"uniswap.bike",
"uwallet.com",
"validateddappsconnect.com",
"wallets-walletconnect.com",
"wcvalidate.org",
"xn--thr-dna.financial",
"xtztoken.site",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Get rid of dupes:
```
    +   "metamask.laconfianzacoop.com",
    +   "metamaskreward.com",
    +   "wallets-walletconnect.com",
```

Get rid of FP

```
"stanbridgemill.com",
```

Add
```
helpuser.org
makfisk.top
opensail.app
```

**Review by dubstard — COMMENTED** [review]
"appsecurenode.com",
"mainaffix-sync.com",
"mainnode-sync.com",
"mainsyncnode.com",
"nftland-app.com",
"noderectifysyncs.com",

all conveniently hosted on the same Lithuanian IP...

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thank you

**Pull request merged**
