### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
airdroptrust.xyz|https://user-images.githubusercontent.com/49607867/164371963-74019a78-03d7-450a-9ad6-8794c88a2e1a.png
app.yoroiwebwallet.com|https://user-images.githubusercontent.com/49607867/164372512-95e17ce6-5160-4c2d-98ae-d82050d1e43a.png
coinbebit.com|https://user-images.githubusercontent.com/49607867/164372579-6a28b034-18c5-4bb5-bbfa-77bb5ea970f3.png
integratedrollcollab.online|https://user-images.githubusercontent.com/49607867/164371884-b59434f9-ee21-449e-a119-b948d64ce930.png
workonminworld.com| https://urlscan.io/result/0d015012-9b06-4a3a-97a6-cddfa542e06f/dom/
nodeapend.nodesdefiwnet.online|https://urlscan.io/result/18dccc4f-43a2-43f5-b6e5-9bccc1f9cceb/dom/
polygon.appecosystem.org|https://user-images.githubusercontent.com/49607867/164372717-60839bec-6b87-4d8d-b1e4-68c5bb3754c6.png
entries.pch-lc.com|https://user-images.githubusercontent.com/49607867/164373171-374b9bcd-3a7e-4646-9b2c-1599a633586b.png
syndefidapp.com|https://urlscan.io/result/d98a3eeb-b5ef-41e8-963e-a91c15dc48f6/dom/

</body>
</html>

Add

"accessfixapp.com",
"activacionstracash.info",
"airdroptrust.xyz",
"app.instantfix.net",
"app.yoroiwebwallet.com",
"appecosystem.org",
"coinlee.live",
"coinsecure.live",
"colinlandds.buzz",
"cryptomaxbase.com",
"coinbebit.com",
"damsbit.com",
"dbridgenode.netlify.app",
"entries.pch-lc.com",
"hawkminer.com",
"integratedrollcollab.online",
"mowett.xyz",
"nodeapend.nodesdefiwnet.online",
"nodeapend.online",
"nodesdefiwnet.online",
"openlandnft.com",
"polygon.appecosystem.org",
"pumpwalletnft.net",
"stenp.shop",
"syndefidapp.com",
"truistwallet-com.tk",
"u-veryfication.com",
"validate.defiease.net",
"validation-whitelist.com",
"wallet.accessfixapp.com",
"workonminworld.com",
"yoroiwebwallet.com",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicates
    -   "collablandtools.com",
    -   "dappspublicchains.com",
    -   "instantfix.net",
    -   "launchdapps.netlify.app",
    -   "mainnetwalletconnects.com",
    -   "syncdappconnect.com",
    -   "walletconnectrectification.support",
add
"coinbebit.com",

**Review by dubstard — COMMENTED** [review]
add "syndefidapp.com",

**Comment by dubstard** [comment]
✅Ready for review

**Review by ical10 — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
