### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
image
Scam, stealing seed

### CODE REVIEW

**Review by jacogr — APPROVED** [review]
Another day, yet another "lemme have your seed" site. I don't know if these are just -

(a) very low effort
(b) very profitable

Probably a combination of both.

**Comment by dubstard** [comment]
You wont believe what explanations the scumbags give to users they try to bait on discord
_"It is safe, bro, it is encrypted using SSL TLS 256 super safe bro, check out that padlock"_

**Comment by dubstard** [comment]
What lures scammers is the potential profit / against chances of getting caught ratio,

As registrars happily deal with "Jhon Doe", to provide both Hosting and Domain registration to literal cyber criminals who registered using a temporary email address in Seychelles.

Then even if the affected entity (bank, institution, organization) does bother to dispatch an attorney signed subpoena to reveal the identity of the culprit, the registrars **literally do not know who they are dealing with**, but still happily collect profit from them, all day, every day.

And can not implement a single regular expression to monitor for bad keywords ()example covid19), [despite the fact that they boast how they "proactively" fight cyber crime.](https://twitter.com/dubstard/status/1334015689552695296)

So crimesters are not worried of getting caught, because registrars are active co conspirators to commit fraud, but they act as if they play fair and "very much care about fraud".
Essentially the registrars profit as well, eventhough they claim fraud costs them money.

They also wash away responsibility by saying (we have contracts with anti phishing companies X, Y and Z, see how much we care"
They do act upon takedown requests, but the bad sites exists for enough time to fuel the scam operations for years ahead.

Until registrars are not pressed by ICANN to do AML and KYC, this won't stop.

**Comment by dubstard** [comment]
Saved the polkadot logo used by scammers, hashed it, and searched for the hash - found other scams re using the same file.
image

that way even completely random domains that do not contain `polkadot` in the TLD or FQDN can still be found and sent for take down enforcement.

**Pull request merged**
