### PR TITLE
Remove non-phishing local sites

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/polkadot-js/phishing/issues/831

### CODE REVIEW

**Comment by jacogr** [comment]
cc @dubstard cc @michalisFr cc @ical10 

A double-check and review here would be good

**Comment by ical10** [comment]
At a first glance, they seem harmless to me.
Screenshots:
Screen Shot 2022-01-21 at 13 56 18
Screen Shot 2022-01-21 at 13 56 14
Screen Shot 2022-01-21 at 13 56 07
Screen Shot 2022-01-21 at 13 56 03

**Comment by michalisFr** [comment]
Same as https://github.com/polkadot-js/phishing/pull/985
I think these are harmless but I'll report them for monitoring, in case their use changes.

**Comment by dubstard** [comment]
They can appear harmless but without extensive fuzzing, scanning for sub domains and payloads there is no concrete way to tell.
Also worth noting any of them can be weaponized at any given point even if they do not serve phish, simply as TLD for emails - in fake tech support scams
`Hey write to ResolveWalletIssue@ScammyCyberSquatDomain.top`

**Pull request merged**
