### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
autoconnectsapp.com|https://urlscan.io/result/d40729be-c386-4354-b62c-112ff8d7bf5b/
dapwalletconnect.com | https://urlscan.io/result/c58d082a-c076-4959-911c-da8360e79952/
defisupport.live|https://urlscan.io/result/8d5e954a-9809-46e6-963c-fae9d0d1b745/
sale-ico.com  | https://urlscan.io/result/453becb9-dd9f-4832-bf92-c8b2776c762f/
solvewalletconectsproblems.com|https://urlscan.io/result/859ace5c-4936-4878-b6d1-5da64cf6f0b8/
walletappconectsolution.com|https://user-images.githubusercontent.com/49607867/160232312-89093ad2-db0d-4956-a5e0-6487c3816a46.png

</body>
</html>

"autoconnectsapp.com",
image
image

"dapwalletconnect.com", 
image
image

"defisupport.live",
image
image

"sale-ico.com",
image
image

"solvewalletconectsproblems.com",
image
image

"walletappconectsolution.com", (UrlScan Geofenced- fake 404 page)
image

"boredapeyachtclubcoin.com", (no dot, excluding from table)
image

### CODE REVIEW

**Comment by dubstard** [comment]
`| const TOP_LEVEL = [`
` |   'ddns.net',`
Seems it comlains about a constraint, but i dont have any ddns gTLD sites in my PR

**Review by dubstard — COMMENTED** [review]
added missing comma

**Review by dubstard — COMMENTED** [review]
add fresh scam, h/t megamind
"defisupport.live",

**Review by ical10 — APPROVED** [review]

**Comment by dubstard** [comment]
Aye, thanks!

**Pull request merged**
