### PR TITLE
update all.json

### PR DESCRIPTION
**Pull request by ical10**
|Site|Urlscan|
|--|--|
|auth.smartdappfix.com|https://urlscan.io/result/640abb7c-3b6d-48fb-bb0b-bc620f4cf5b9/|
|auto-dapprectify.com|https://urlscan.io/result/f183b798-0b83-4acf-8a63-6280bc19f8a6/|
|autoethcalibrator.com|https://urlscan.io/result/cecb0383-26fc-4564-a520-ff5e1bd121c5/|
|dappsconnection.net|https://urlscan.io/result/8f9f1a54-f420-414a-a223-af20e7bceb74/|
|dnodeapp.netlify.app|(parity signer) https://urlscan.io/result/9a4105b0-4b0b-4a38-88fa-eb2f1afe8e1e/dom/|
|joint-validation.online|https://urlscan.io/result/26ac29bd-b2da-4b15-b567-07d7d2a07a48/|
|launchdapps.netlify.app|https://user-images.githubusercontent.com/14356826/164366264-e31ebb30-be06-4f5b-9144-bbab6d47e990.png|
|little-cronos.com|https://urlscan.io/result/81950816-09ba-421d-8741-e906cbc32aea/|
|sourcevalidations.net|https://urlscan.io/result/02638d9f-e67d-49a8-b443-425dc4ba6ade/|
|syncwallet.tk|https://urlscan.io/result/719a4ee7-2c19-4cc6-8c7d-5d290a4cb0b7/|
|uniconnect.live|https://urlscan.io/result/62414196-1d7d-478d-96c7-4536ad4e5d86/|
|wallet-dappsintegration.uk|https://urlscan.io/result/653bf4b5-3207-4032-b835-62580be21c5f/|
|web3host.tech|(parity signer) https://urlscan.io/result/a55a1276-542c-4bbf-ac21-c1b83ad690a9/dom/|
|webresolve.live|https://urlscan.io/result/b68d94a1-f294-4b89-b52f-dcbc7d656d18/|

auto-dapprectify com_SITE
autoethcalibrator com_SITE
dappsconnection net_SITE
dnode netlify app_SITE
joint-validation online_SITE
launchdapps netlify app_SITE
little-cronos com_SITE
sourcevalidations net_SITE
syncwallet tk_SITE
uniconnect live_SITE
wallet-dappsintegration uk_SITE
web3host tech_SITE
webresolve live_SITE

### CODE REVIEW

**Comment by ical10** [comment]
WIP
creating table, screenshots, and adding TLDs

**Comment by ical10** [comment]
done, ready for review 🚀

**Comment by dubstard** [comment]
Haha what is this duck with the shotgun, lmao

**Review by dubstard — APPROVED** [review]
Looks good to me, has both screenshots and URLScans, implementer went the extra mile, nicely done.

**Comment by ical10** [comment]
thanks dubstard!

**Pull request merged**
