### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
autodappreauth.xyz|https://urlscan.io/result/36c4c88d-fc9f-414a-8597-ef2fadc67d12/dom/
cryptowallsconnet.com|https://urlscan.io/result/4f4e3589-017f-4238-9758-cc5e4af5d7a2/dom/
walletsvalidatenow.net|https://user-images.githubusercontent.com/49607867/164878458-d8db1e6d-5635-4f3b-aa11-b0712a713804.png
imtoken-vip.info|https://user-images.githubusercontent.com/49607867/164878469-2ab36ecb-a0b1-4af7-a00e-3f3b51d9ba06.png
imtokensn.com|https://user-images.githubusercontent.com/49607867/164878492-9a1fe9f2-e5ad-4651-b677-46023522994f.png
digitaldappsyncs.online|https://urlscan.io/result/1432a95b-a4a3-483c-b41b-f982bba88eb4/
i-mtioken.club|https://user-images.githubusercontent.com/49607867/164878542-6a9e3889-9085-4851-b07c-4e833a84e70c.png
wcencrypt.online|https://user-images.githubusercontent.com/49607867/164878555-decd7a63-c5f7-42b2-b3cd-bcf74cbd93d0.png
connectmywallets.org|https://user-images.githubusercontent.com/49607867/164878570-899b8891-eb5a-4852-a930-cf9b782ff6ae.png
walletauthentications.pancakesswappfinance.com|https://user-images.githubusercontent.com/49607867/164878596-becad8f8-2374-4f01-b5ec-594bf3f5cb37.png

</body>
</html>

"apptokens.xyz",
"authenticatenode.online",
"autodappreauth.xyz",
"badapplesiphonerepair.com",
"bridgeportconnecticut.net",
"bswaptoken.online",
"collablandapp.net",
"cryptokens.site",
"cryptokittiesdapp.xyz",
"cryptowallsconnet.com",
"daperlabsdapp.art",
"daperlabsdapp.xyz",
"daperlabstoken.art",
"daperlabstoken.xyz",
"dapp-eth.tips",
"dapp-eth.zone",
"dapperlabs.space",
"dapperlabs.website",
"dapperlabsblockchain.art",
"dapperlabsblockchain.space",
"dapperlabsblockchain.website",
"dapperlabsblockchain.xyz",
"dapperlabscoin.space",
"dapperlabscoin.top",
"dapperlabscoin.website",
"dapperlabscoin.xyz",
"dapperlabscollectable.art",
"dapperlabscollectable.space",
"dapperlabscollectable.website",
"dapperlabscollectable.xyz",
"dapperlabscollectible.art",
"dapperlabscollectible.space",
"dapperlabscollectible.top",
"dapperlabscollectible.website",
"dapperlabscollectible.xyz",
"dapperlabscrypto.art",
"dapperlabscrypto.space",
"dapperlabscrypto.top",
"dapperlabscrypto.website",
"dapperlabscrypto.xyz",
"dapperlabsdapp.art",
"dapperlabsdapp.space",
"dapperlabsdapp.xyz",
"dapperlabsdecentralized.art",
"dapperlabsdecentralized.space",
"dapperlabsdecentralized.website",
"dapperlabsledger.art",
"dapperlabsledger.space",
"dapperlabsledger.top",
"dapperlabsledger.website",
"dapperlabsledger.xyz",
"dapperlabsmoment.art",
"dapperlabsmoment.space",
"dapperlabsmoment.xyz",
"dapperlabsnft.art",
"dapperlabsnft.space",
"dapperlabsnft.website",
"dapperlabsnft.xyz",
"dapperlabstoken.art",
"dapperlabstoken.space",
"dapperlabstoken.website",
"dapperlabstoken.xyz",
"dapperlabswallet.art",
"dapperlabswallet.space",
"dapperlabswallet.top",
"dapperlabswallet.website",
"dapperlabswallet.xyz",
"dapperllabs.art",
"dapperllabs.xyz",
"dapperllabsblockchain.art",
"dapperllabsblockchain.xyz",
"dapperllabscoin.art",
"dapperllabscoin.xyz",
"dapperllabscollectable.art",
"dapperllabscollectable.xyz",
"dapperllabscrypto.xyz",
"dapperllabsdapp.xyz",
"dapperllabsdecentralized.xyz",
"dapperllabsledger.art",
"dapperllabsledger.xyz",
"dapperllabsmoment.art",
"dapperllabsmoment.xyz",
"dapperllabsnft.xyz",
"dapperllabstoken.xyz",
"dapperllabswallet.art",
"dapperllabswallet.xyz",
"dappgrader.com",
"dappstore.pro",
"dcrv2.xyz",
"deservedapp.net",
"dexbridge.xyz",
"digitaldappsyncs.online",
"eurotoken.live",
"evmtoken.xyz",
"flowdapp.net",
"flowdapp.space",
"flowdapp.website",
"flowdapp.xyz",
"flowtoken.space",
"i-mtioken.club",
"imitoken.info",
"imtoken-hk.xyz",
"imtoken-sib.site",
"imtoken-sib.top",
"imtoken-sib.website",
"imtoken-sib.xyz",
"imtoken-vip.info",
"imtokensn.com",
"letstoken.com",
"linkbridge.xyz",
"lltokenn.xyz",
"meta-mas.com",
"microconnectoken.net",
"microconnectoken.one",,
"nodebridge.xyz",
"polygos-tecnology.live",
"token-pay.pro",
"tokencreate.online",
"tokenners.online",
"tokenpcooket.pro",
"tokenpcooket.xyz",
"tokenpocketi0.xyz",
"tokenswap.world",
"turst-wallet.cam",
"ua-donate.com",
"utokenwallet.xyz",
"verify-account.net",
"verifyassets.net",
"verifyownership.xyz",
"walletbridge.xyz",
"walletsvalidatenow.net",
"wcencrypt.online",
"webbridge.xyz",
"walletauthentications.pancakesswappfinance.com",
"pancakesswappfinance.com",
"unisswapp.com",
"trustwallet.com.upgradepage.cc",
"upgradepage.cc",
"helpukraine2022.online",
"walletsauthorization.net",
"phantom-app.website",
"polygon-tehnology.website",
"xtoken.win",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
fix double ,,

add "connectmywallets.org",

**Review by dubstard — COMMENTED** [review]
remove duplicates
 "phantom-app.website",
  "verifyassets.net",

**Comment by dubstard** [comment]
✅Ready for review

**Review by ical10 — APPROVED** [review]

**Comment by dubstard** [comment]
Thank you!

**Pull request merged**
