### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
connectswalletdapp.com|https://user-images.githubusercontent.com/49607867/164958502-11af49a8-8d2a-475d-86fb-6b14681e3a26.png
cryptoswalletsconnect.com|https://urlscan.io/result/b94dfcbd-b366-4e6e-b001-6ee1b00b96d3/dom/
metamask.bonuscriptomoedas.com|https://user-images.githubusercontent.com/49607867/164958383-4ca482fb-2521-4b43-b0d5-528ef5536dd1.png
noderesolve.com|https://user-images.githubusercontent.com/49607867/164958408-c3d300a2-9300-459f-b3bb-91a880a96df9.png
mainnetsync.net|https://urlscan.io/result/eae3e024-fcf5-4b12-83e3-0be0c934b9df/dom/
standardglobaltrading.com|https://user-images.githubusercontent.com/49607867/164958479-4d621eb6-1487-49d6-88b1-b28560d08843.png
wallarttautl.com|https://urlscan.io/result/9667d5ca-4b34-4fcc-a4fe-1d92ecf6e4e2/dom/
walletsrectificationdapp.com|https://user-images.githubusercontent.com/49607867/164958511-fd2292f1-88f1-46a6-a6d0-33f24f565052.png
cravedappstect.com|https://urlscan.io/result/03bbacfd-fa0d-49b9-b9a7-732a8579d6c1/dom/
mainnetsdapp.online|https://user-images.githubusercontent.com/49607867/164960114-7a6c4510-652a-4c14-9b9f-a620bca058a4.png
smartsynchronization.com|https://user-images.githubusercontent.com/49607867/164960157-4895f143-d4f8-4091-9704-ba7de1f4b9cf.png
tokenpockot.net|https://urlscan.io/result/f64d06cf-d589-4b02-b8c4-878592a38f46/dom/
blockbridge.tools|https://urlscan.io/result/6c633285-8d20-41cb-9788-334ff33ad055/dom/
fixedapp.xyz|https://urlscan.io/result/9e2b8c8b-40f4-4a1c-ba44-91ae683c3237/
fixedapps.xyz|https://urlscan.io/result/05813a9c-e7f4-4ac4-80b7-20f3b72af723/
synchronize-dapps.com|https://user-images.githubusercontent.com/49607867/164960475-9d54b2ff-e2d4-4e0b-be16-dd98493b0c18.png
tokenpocrket.pro|https://urlscan.io/result/2e173970-3d66-4051-918c-982df7b3f3c1/dom/
tokenpocsket.pro|https://urlscan.io/result/59988755-6db6-4989-8d98-504fc4baee99/dom/
tokenpocxket.pro|https://urlscan.io/result/8361f33e-ef2a-483a-9dd4-8b8575c9ba0f/dom/
walletsconnect-in.com|https://user-images.githubusercontent.com/49607867/164960590-9f4d9527-3e08-4b07-936f-b40da9ede188.png
walletsencrypts.com|https://urlscan.io/result/2800d680-1c35-49db-9800-7dfe32d7186e/dom/

</body>
</html>

```
"1inchoficial.bonuscriptomoedas.com",
"bride-terra.money",
"claim-ape.land",
"claim-murakami.com",
"connectswalletdapp.com",
"cryptoswalletsconnect.com",
"help-tool.net",
"io-metamask.redirectme.net",
"kyberswep.com",
"mainnetauth-interface.org",
"mainnetsync.net",
"metamask-onlineconnect.com",
"metamask-web-utils-prod.app.greate.eu",
"metamask.bonuscriptomoedas.com",
"metamask.coralscookiesinc.com",
"metamask.ventures",
"metamaskdenemex.tk",
"metamaskwebwallet.io",
"mojitoswap.io",
"mojitoswap.org",
"mojitoswep.finance",
"mpsienaantifrode.com",
"netswep.io",
"noderesolve.com",
"olympusdaos.app",
"pancakeswap.org",
"polkaswep.io",
"secure02e.com",
"standardglobaltrading.com",
"terras-money.com",
"trust.binancbrasil.com",
"usernode.org",
"vitalik-ether22.net",
"wagyuswap.exchange",
"wagyuswap.finance",
"wagyuswep.app",
"wallarttautl.com",
"walletsrectificationdapp.com",
"cravedappstect.com",
"mainnetsdapp.online",
"smartsynchronization.com",
"tokenpockot.net",
"blockbridge.tools",
"dapps-mnemonic-protocol.online",
"fixedapp.xyz",
"fixedapps.xyz",
"synchronize-dapps.com",
"tokenconnectfixer.com",
"tokenpocrket.pro",
"tokenpocsket.pro",
"tokenpocxket.pro",
"verification-walet.online",
"walletsconnect-in.com",
"walletsencrypts.com",
```

there are also 

<html>
<body>

Site | URLScan link
-- | --
test.polkadotwallet.de|https://user-images.githubusercontent.com/49607867/164958657-c32f14df-5328-4e0e-83d0-0cc02a8eef7e.png
app.polkadotwallet.de|https://user-images.githubusercontent.com/49607867/164958643-ea5560b8-8c60-4454-8940-461293054d83.png
blog.polkadotwallet.de|https://user-images.githubusercontent.com/49607867/164958651-09e6011e-ebcf-4f41-908f-97b334d42574.png
web.polkadotwallet.de
wordpress.polkadotwallet.de
en.polkadotwallet.de

</body>
</html>

which i have not blocked (yet), but they don't look promising

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove "cryptoswalletsconnect.comreg.html", (invalid url)

**Review by dubstard — COMMENTED** [review]
add
"cravedappstect.com",
		"mainnetsdapp.online",
		"smartsynchronization.com",
		"tokenpockot.net",
		"blockbridge.tools",
		"dapps-mnemonic-protocol.online",
		"fixedapp.xyz",
		"fixedapps.xyz",
		"synchronize-dapps.com",
		"tokenconnectfixer.com",
		"tokenpocrket.pro",
		"tokenpocsket.pro",
		"tokenpocxket.pro",
		"verification-walet.online",
		"walletsconnect-in.com",
		"walletsencrypts.com",

**Comment by dubstard** [comment]
WIP adding screenshots URLscans

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thank you!

**Pull request merged**
