### PR TITLE
update all.json

### PR DESCRIPTION
**Pull request by ical10**
|Site|Urlscan|Screenshot|
|--|--|--|
|link-bridge.live|https://urlscan.io/result/8ddc1c4c-559d-4718-955b-3a61a4594224/dom/|https://user-images.githubusercontent.com/14356826/180657835-56ce9595-470f-4ec7-a564-d2c8c5b6e89d.png|
|bridgenewcontract.live|https://urlscan.io/result/f7f47679-904f-4920-95d4-7dcdc6da31d1/|https://user-images.githubusercontent.com/14356826/180657836-63e95e3c-1e6f-400d-9cfc-73578234927a.png|
|v2tokenmigration.live|https://urlscan.io/result/76ab1617-eb6e-4ab8-ac48-53d4e0c8619b/|https://user-images.githubusercontent.com/14356826/180657832-54ed1c50-5d07-4810-88cc-0e2d1a702332.png|
|v2tokenbridge.live|https://urlscan.io/result/3f96b8d2-b9cf-4913-b723-d5ad7cb60734/|https://user-images.githubusercontent.com/14356826/180657838-655e15c8-cdd5-44c9-bcf8-591631dc0d31.png|
|polkadottoken.live|https://urlscan.io/result/536ba71e-911b-409d-acc8-3aea030eec6d/|https://user-images.githubusercontent.com/14356826/180657840-426c299b-ec8c-4cf8-a436-c8c95fc51de9.png|
|appauthes.in.net|https://urlscan.io/result/ad4ac09d-b9a7-43df-9b48-7c9ac281ac2d/|https://user-images.githubusercontent.com/14356826/180657842-6140de08-8ef8-441d-baa0-808bd17dc476.png|
|s.smartsync-protocol.live|https://urlscan.io/result/a5cc4365-079e-41fb-a9bf-85140221cee9/|https://user-images.githubusercontent.com/14356826/180657855-dcfc149f-da27-45a9-8982-2ba7a62e0ffb.png|
|smartaffixs-protocol.live|https://urlscan.io/result/28ffb1de-6a55-4434-8b05-533894a76141/|https://user-images.githubusercontent.com/14356826/180657856-ea5cc805-f031-4de9-98bd-da3579e6ded7.png|
|loyaprotocol.live|https://urlscan.io/result/476ac03f-5883-45fb-8e2e-61395462c380/dom/|https://user-images.githubusercontent.com/14356826/180657859-f50b1ebd-62ba-4f5a-b966-7d4824968250.png|
|connectprotocol.live|https://urlscan.io/result/0700ea9f-3784-4fe2-aaae-d2e1c5e806d5/dom/|https://user-images.githubusercontent.com/14356826/180657861-3d64f41e-e148-423b-ad1e-be2f22acedaa.png|
|crosswebfix.live|https://urlscan.io/result/e2b35260-8104-4512-9747-bac9ffdb1178/|https://user-images.githubusercontent.com/14356826/180657852-8b629d80-2d6a-454c-9f42-3c8af78e3f22.png|
|metadappsfixer.live|NA|https://user-images.githubusercontent.com/14356826/180657850-03c57336-4abd-407e-9d69-579a24061ad3.png|
|superwebfix.live|https://urlscan.io/result/72a46797-141a-4a53-a6f4-912e3b0d8ca5/|https://user-images.githubusercontent.com/14356826/180657848-581e9122-cc2e-48dc-a2cd-08846f0a0559.png|

### CODE REVIEW

**Review by jacogr — APPROVED** [review]

**Comment by ical10** [comment]
Thanks Jaco!

**Comment by thwjanssen89** [comment]
This is not in correct format yet

**Comment by thwjanssen89** [comment]
Nice finds btw. Quite a lot, you have been busy ;)

**Comment by ical10** [comment]
Let's catch all of them @thwjanssen89 :P

**Pull request merged**
