### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
```
"multi-connect.servehttp.com",
"̶s̶e̶r̶v̶e̶h̶t̶t̶p̶.̶c̶o̶m̶"̶,̶
"multifaucetconnect.online",
```

I have never seen a legitimate `*.servehttp` site
This is a legit service by `no-ip.com` which gets so much misuse, it is a safest bet to block it altogether.

Same goes for the free to register freenom domains such as `.gq` `.ml` `.ga` `.cf` and also `.tk`
image
image

image

### CODE REVIEW

**Review by jacogr — COMMENTED** [review]
Not 100% convinced by servehttp.com since it is legit. (Although easily misused)

**Comment by dubstard** [comment]
I agree and I know it is legit by nature.

It is simply that [very few (close to none) legitimate sites exist that use it.](https://urlscan.io/search/#page.domain%3A(servehttp.com))
image

**Review by dubstard — COMMENTED** [review]
remove `"̶s̶e̶r̶v̶e̶h̶t̶t̶p̶.̶c̶o̶m̶"̶,̶`

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks Jaco, sorry for the trouble and being overzealous

**Pull request merged**
