### PR TITLE
update all.json

### PR DESCRIPTION
**Pull request by ical10**
|Site|Urlscan|
|----|----|
|proultranft.com|https://urlscan.io/result/4afd6592-5b73-4da5-a31c-afae3593c9fe/|
|app.dappfixedconnect.net|https://urlscan.io/result/f08f16aa-9a87-4685-adcf-079797c19b99/|
|connectwalet.com|https://urlscan.io/result/f0acde21-a0b7-4ecf-a987-3108a8d5c87c/|
|dappwalletconnections.com|https://urlscan.io/result/73b37a6f-4aa5-4d8e-a298-19f8fafa2152/|
|walletconnectionerror.com|https://urlscan.io/result/50702860-e53d-45c6-a73a-d4f1fb3c59b3/|

proultranft com_SITE
app dappfixeconnect net_SITE
connectwalet com_SITE
dappwalletconnections com_SITE
walletconnectionerror com_SITE

### CODE REVIEW

**Comment by ical10** [comment]
my Coc is acting up, sorry I had to close the first two since it modified the whole json file

**Comment by jacogr** [comment]
That was me - I changed the files to tabs. Sorry :(

**Review by jacogr — APPROVED** [review]

**Comment by ical10** [comment]
Ah, no worries. Why we changed from space to tabs? Just curious.

**Comment by jacogr** [comment]
There is obviously the fact that it does create an initial issue for existing contributors (where everything changed) as you saw. However it doesn't really matter if you make a PR with spaces or tabs, CI will reformat it anyway when it does the sorting, so either is fine for adding.

The tabs made around a 20k/8% difference on the all.json file. In practice, over the network, this doesn't really matter since it will be served via gzip or brocolli compression anyway, however even a tiny space saving on the parsing side does always improve things.

In a perfect world, for machine consumption, serving it completely devoid of formatting is best, however that it not really usable for any manual editing. Sometime in the future, will most probably keep all.json (and allow additions to it) and then let CI split it into something like `deny.json` which is then for machine consumption only...

**Comment by ical10** [comment]
Oh, thanks for the detailed explanation! Never thought of this before.

I'm all for improvement.

**Pull request merged**
