### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
```
"automaticdexvalidate.com",
"dappresolve.io",
"iwalletsbrowser.net",
"networkchainid.com",
"rectbloks.org",
"metamasklinking.org",
"decentrala.cam",
"trustwalet.vip",
"syncingwallet.online",
"walletsconnect.gcf-online.com",
"gcf-online.com",
"updateswallets.com",
```
`dappresolve.io`
image

`rectbloks.org`
image

`walletsconnect.gcf-online.com`
image

`updateswallets.com`
image

<html>
<body>

Site | URLScan link
-- | --
dappresolve.io| Site taken down before i was able to mirror it, but there is a screenshot
rectbloks.org|https://urlscan.io/result/43ea38ca-ddfc-4466-8679-c8d51c2686f7 Site taken down before I was able to mirror it, but there is a screenshot)
walletsconnect.gcf-online.com|https://urlscan.io/result/eddaccff-c9a9-4b30-9cc5-91335715ad8a/
updateswallets.com|https://urlscan.io/result/eddaccff-c9a9-4b30-9cc5-91335715ad8a/

</body>
</html>

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupes

**Review by dubstard — COMMENTED** [review]
add
```
    "walletsconnect.gcf-online.com",
    "gcf-online.com",
```

**Review by dubstard — COMMENTED** [review]
add `"updateswallets.com",`

**Review by jacogr — APPROVED** [review]

**Comment by dubstard** [comment]
Should be good to go now!

**Pull request merged**
