### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
authenharmonizedapps.online|https://user-images.githubusercontent.com/49607867/167287078-4e220778-a87f-4138-b92f-447aa5b26f26.png
cryptobasedapps.cloud|https://urlscan.io/result/eef4c5a7-8991-41d3-93ad-a4f2844d1f46/dom/
collabslands.org|https://user-images.githubusercontent.com/49607867/167284883-9d3afc5c-1a2a-4cac-b347-4d10fa3eaae5.png
dapp-pool.live|https://user-images.githubusercontent.com/49607867/167286904-428aa380-cd13-430d-828f-6ea2e12bf1cb.png
holiday-rental.online|https://urlscan.io/result/df750c4f-3cfd-4152-beca-5784b4dbf818/dom/
imtokenlo.tech|https://urlscan.io/result/0caed7ee-ff80-4f2e-9b45-a400df45c48b/dom/
tokenpocket-apps.net|https://urlscan.io/result/3b305d92-a749-419f-b440-369ffb331d13/dom/
tokenpockat.club|https://urlscan.io/result/a251dbc2-6f4e-4a42-9ec2-99814408ba0f/dom/
topdogtokenswap.com|https://urlscan.io/result/27faafbd-3aee-4f96-9a97-c9292fa509a6/dom/
solutionwalletapp.com|https://user-images.githubusercontent.com/49607867/167287019-d9ce90c8-d214-4858-9372-784a228f9115.png

</body>
</html>

"authenharmonizedapps.online",
"beefy.cloud",
"bridge-terra-go.sbs",
"bridgeterra-go.sbs",
"coinbasewallet.win",
"connectodapp.com",
"cryptobasedapps.cloud",
"dappwallet.support",
"discordappinvite.com",
"imtoken-im.app",
"imtokenlo.tech",
"metamasklivesupport.vercel.app",
"nodewalet.com",
"s-tepn.online",
"shibatoken-go.space",
"shibatoken-x2.com",
"shibatokengo.sbs",
"skdnbekejsgejsjidodhebejosiduxhenwksppdocjdjeowpsmd.site",
"sltepn.space",
"sntepn.space ",
"stapan.online",
"stapan.website ",
"stepncom.space",
"ticket-magiceden.io",
"tokenpockat.club",
"tokenpocket-apps.net",
"walletshiba.website",

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupes
"dappconnection.online",
"metamaskcan.xyz",

add
"holiday-rental.online",

**Review by dubstard — COMMENTED** [review]
trim extra spaces breaking the json
add

"collabland.in",
"collabslands.org",

How to gauge if a project is successful: If you see 10 scams per day, it probably means that this is a big project with potential.
Check this one out, lmao:

```
Real
/stepn.com

Fake
/stepn-nft.space
/stepn-nft.shop
/stepn.nfts-mint.net
/stepn-asics.site
/stepnactivation.org
/stepn.bond
/stepncom.space
/sntepn.space 
/s-tepn.online
/sltepn.space
/stapan.website 
/stapan.online
```

```
Real: https://collab.land

Fake:  collablands.biz 
collab-land.bid
c.ollab.land
debug-collab.land
syncmycollab.me
nftcollab.land
colablanddefi.info

IoC:
https://twitter.com/dubstard/status/1503329493435490306
https://twitter.com/dubstard/status/1490561706510237696
https://twitter.com/dubstard/status/1490655569434361856
https://twitter.com/dubstard/status/1485254487971348482

Twitter: https://twitter.com/Collab_Land_
```

**Review by dubstard — COMMENTED** [review]
"dapp-pool.live",
		"verify-coinbase.sesamiclothings.com",
		"webwalletsauthenticate.com",

**Review by dubstard — COMMENTED** [review]
add
"topdogtokenswap.com",
"solutionwalletapp.com",

h/t ecarlesi for those 2

**Comment by dubstard** [comment]
✅Ready for review

**Review by frankywild — APPROVED** [review]

**Comment by dubstard** [comment]
thanks

**Pull request merged**
