### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by dubstard**
<html>
<body>

Site | URLScan link
-- | --
api3drop.com|https://user-images.githubusercontent.com/49607867/159850121-64ffa28c-7dbc-4cfc-9890-e412dbc85bbf.png
auth-dapps.net|https://urlscan.io/result/867f938e-3a2b-43ad-841e-0de59be09f07/
chainapprovals.com|https://urlscan.io/result/6ac6bf5e-5952-44ad-94a1-52ed918dcc4f/
dappwlvalidator.online|https://user-images.githubusercontent.com/49607867/159855537-4e74b476-9959-4080-86d6-483f424c04a4.png
get-free-crypto-tokens.online|https://urlscan.io/result/131a5f87-d1c1-42fb-863c-b67b08cbb863/
metamasksolutions.wconectdapp.com|https://user-images.githubusercontent.com/49607867/159852322-21c41678-b9a3-45d1-a44f-c052ddab322d.png
mymultinodes.icu|https://user-images.githubusercontent.com/49607867/159854222-3c9cb855-715f-4e44-beec-fd544f4bed94.png

</body>
</html>

`api3drop.com`
image

`auth-dapps.net`
image

`chainapprovals.com`
image

`dappwlvalidator.online`
image

`metamasksolutions.wconectdapp.com`
image

`get-free-crypto-tokens.online`
image

mymultinodes.icu (h/t @ecarlesi )
image

`s-walletsync.com`
image

```
"api3drop.com",
"auth-dapps.net",
"chainapprovals.com",
"china-metamask.io",
"crypto-wallets.com",
"dappswapp.com",
"dappwlvalidator.online",
"get-free-crypto-tokens.online",
"mainnetdappbot.net",
"metamask-blockchain.com",
"metamask-token.link",
"metamask-zz.wiro-apps.org",
"metamasksolutions.wconectdapp.com",
"mymultinodes.icu",
"polkadotcoin.org",
"s-walletsync.com",
"tokenconect.click",
"wconectdapp.com",
```

### CODE REVIEW

**Review by jacogr — APPROVED** [review]

**Review by dubstard — COMMENTED** [review]
+"auth-dapps.net",

**Review by dubstard — COMMENTED** [review]
+ "s-walletsync.com",

**Comment by jacogr** [comment]
You should be able to merge - 

- there is 1 approval
- CI passed

**Comment by dubstard** [comment]
Thanks and apologies for editing post the approval.
(I found some more while editing.)

**Comment by jacogr** [comment]
Ummm... seem like a permissions issue, Lemme check :(

**Comment by jacogr** [comment]
Hopefully now...

**Comment by dubstard** [comment]
OMG it might have been brave Browser. I disabled the Shields up (noScript) and now it is green!

**Comment by jacogr** [comment]
Cool, click it. (I believe it was indeed a permissions issue the team didn't have access - there are too many levers to pull on the setup side, so not surprised I missed some...)

**Comment by dubstard** [comment]
Great success! 😎🆒

**Pull request merged**
